// Character -> native card pool mapping for Slay the Spire 2
// Cards outside a character's pool that appear during a run are treated as
// belonging to the character playing (cross-character card tracking).
//
// This mapping is used to detect cross-character cards for display purposes.
// ELO is always scoped to the character being played regardless.

const IRONCLAD_CARDS = new Set([
  'CARD.STRIKE_IRONCLAD', 'CARD.DEFEND_IRONCLAD',
  'CARD.BASH', 'CARD.ANGER', 'CARD.ARMAMENTS', 'CARD.BODY_SLAM',
  'CARD.CLASH', 'CARD.CLEAVE', 'CARD.CLOTHESLINE', 'CARD.FLEX',
  'CARD.HAVOC', 'CARD.HEADBUTT', 'CARD.HEAVY_BLADE', 'CARD.IRON_WAVE',
  'CARD.PERFECTED_STRIKE', 'CARD.POMMEL_STRIKE', 'CARD.SHRUG_IT_OFF',
  'CARD.SWORD_BOOMERANG', 'CARD.THUNDERCLAP', 'CARD.TRUE_GRIT',
  'CARD.TWIN_STRIKE', 'CARD.WAR_CRY', 'CARD.WILD_STRIKE',
  'CARD.BATTLE_TRANCE', 'CARD.BLOOD_FOR_BLOOD', 'CARD.BLOODLETTING',
  'CARD.BURNING_PACT', 'CARD.CARNAGE', 'CARD.COMBUST', 'CARD.DARK_EMBRACE',
  'CARD.DISARM', 'CARD.DROPKICK', 'CARD.DUAL_WIELD', 'CARD.ENTRENCH',
  'CARD.EVOLVE', 'CARD.FEEL_NO_PAIN', 'CARD.FIRE_BREATHING',
  'CARD.FLAME_BARRIER', 'CARD.GHOSTLY_ARMOR', 'CARD.HEMOKINESIS',
  'CARD.IMMOLATE', 'CARD.IMPERVIOUS', 'CARD.INFERNAL_BLADE',
  'CARD.INFLAME', 'CARD.INTIMIDATE', 'CARD.LIMIT_BREAK',
  'CARD.METALLICIZE', 'CARD.OFFERING', 'CARD.POWER_THROUGH',
  'CARD.PUMMEL', 'CARD.RAGE', 'CARD.RAMPAGE', 'CARD.RECKLESS_CHARGE',
  'CARD.RUPTURE', 'CARD.SEARING_BLOW', 'CARD.SECOND_WIND',
  'CARD.SEEING_RED', 'CARD.SENTINEL', 'CARD.SEVER_SOUL',
  'CARD.SHOCKWAVE', 'CARD.SPOT_WEAKNESS', 'CARD.UPPERCUT',
  'CARD.WHIRLWIND', 'CARD.BARRICADE', 'CARD.BERSERK',
  'CARD.BLUDGEON', 'CARD.BRUTALITY', 'CARD.CORRUPTION',
  'CARD.DEMON_FORM', 'CARD.DOUBLE_TAP', 'CARD.EXHUME',
  'CARD.FEED', 'CARD.FIEND_FIRE', 'CARD.IMMOLATE',
  'CARD.JUGGERNAUT', 'CARD.REAPER',
  // STS2 additions
  'CARD.TREMBLE', 'CARD.FORTIFY', 'CARD.BLOOD_SURGE',
  'CARD.IRON_CURTAIN', 'CARD.HEMORRHAGE', 'CARD.FURNACE',
  'CARD.MOLTEN_STRIKE', 'CARD.SMOLDER', 'CARD.ERUPTION',
  'CARD.IGNITE', 'CARD.TEMPER', 'CARD.MAGMA_SHIELD',
  'CARD.TORCH', 'CARD.PYROKINESIS', 'CARD.FUEL_THE_FIRE',
  'CARD.HEAT_WAVE', 'CARD.MELT', 'CARD.SCALD',
  'CARD.FORGE', 'CARD.ANNIHILATE',
]);

const DEFECT_CARDS = new Set([
  'CARD.STRIKE_DEFECT', 'CARD.DEFEND_DEFECT',
  'CARD.ZAP', 'CARD.DUALCAST', 'CARD.BALL_LIGHTNING', 'CARD.BARRAGE',
  'CARD.BEAM_CELL', 'CARD.CHARGE_BATTERY', 'CARD.CLAW',
  'CARD.COLD_SNAP', 'CARD.COMPILE_DRIVER', 'CARD.COOLHEADED',
  'CARD.GO_FOR_THE_EYES', 'CARD.HOLOGRAM', 'CARD.LEAP',
  'CARD.REBOUND', 'CARD.RECURSION', 'CARD.STACK',
  'CARD.STEAM_BARRIER', 'CARD.STREAMLINE', 'CARD.SWEEPING_BEAM',
  'CARD.TURBO', 'CARD.AGGREGATE', 'CARD.AUTO_SHIELDS',
  'CARD.BLIZZARD', 'CARD.BOOT_SEQUENCE', 'CARD.BULLSEYE',
  'CARD.CAPACITOR', 'CARD.CHAOS', 'CARD.CHILL', 'CARD.CONSUME',
  'CARD.DARKNESS', 'CARD.DEFRAGMENT', 'CARD.DOOM_AND_GLOOM',
  'CARD.DOUBLE_ENERGY', 'CARD.EQUILIBRIUM', 'CARD.FTL',
  'CARD.FUSION', 'CARD.GENETIC_ALGORITHM', 'CARD.GLACIER',
  'CARD.HEATSINKS', 'CARD.HELLO_WORLD', 'CARD.LOOP',
  'CARD.MELTER', 'CARD.MULTI_CAST', 'CARD.OVERCLOCK',
  'CARD.RAINBOW', 'CARD.REBOOT', 'CARD.RECYCLE',
  'CARD.REINFORCED_BODY', 'CARD.REPROGRAM', 'CARD.RIP_AND_TEAR',
  'CARD.SCRAPE', 'CARD.SEEK', 'CARD.SELF_REPAIR',
  'CARD.SKIM', 'CARD.STATIC_DISCHARGE', 'CARD.STORM',
  'CARD.SUNDER', 'CARD.TEMPEST', 'CARD.THUNDER_STRIKE',
  'CARD.WHITE_NOISE',
  // STS2 additions
  'CARD.SUPERCRITICAL', 'CARD.SHATTER', 'CARD.ICE_LANCE',
  'CARD.SIGNAL_BOOST', 'CARD.OVERCLOCK', 'CARD.FIREWALL',
  'CARD.SURGE', 'CARD.DISCHARGE', 'CARD.CATALYST',
  'CARD.PULSE', 'CARD.CIRCUIT_BREAKER', 'CARD.SYNC',
  'CARD.ECHO', 'CARD.AMPLIFY', 'CARD.DATA_MINE',
  'CARD.MACHINE_LEARNING', 'CARD.HYPER_BEAM',
]);

const REGENT_CARDS = new Set([
  'CARD.STRIKE_REGENT', 'CARD.DEFEND_REGENT',
  'CARD.FALLING_STAR', 'CARD.VENERATE',
  'CARD.ROYALTIES', 'CARD.BUNDLE_OF_JOY',
  'CARD.HIDDEN_CACHE', 'CARD.CELESTIAL_MIGHT',
  'CARD.GATHER_LIGHT', 'CARD.ASTRAL_PULSE',
  'CARD.REFINE_BLADE', 'CARD.CRESCENT_SPEAR',
  'CARD.GLIMMER', 'CARD.PHOTON_CUT',
  'CARD.PILLAR_OF_CREATION', 'CARD.GUIDING_STAR',
  'CARD.RADIANT_GUARD', 'CARD.SOLAR_FLARE',
  'CARD.STARLIGHT', 'CARD.AURORA',
  'CARD.CONSTELLATION', 'CARD.ECLIPSE',
  'CARD.NEBULA', 'CARD.SUPERNOVA',
  'CARD.MOONBEAM', 'CARD.DAWN_BLADE',
  'CARD.DUSK_SHIELD', 'CARD.PRISM',
  'CARD.TWILIGHT', 'CARD.LUMINANCE',
  'CARD.DIVINE_SMITE', 'CARD.CONSECRATE',
  'CARD.HOLY_WATER', 'CARD.BLESSING',
  'CARD.TITHE', 'CARD.DECREE',
  'CARD.CORONATION', 'CARD.ABDICATE',
  'CARD.ROYAL_GUARD', 'CARD.SOVEREIGN_WILL',
]);

const CHARACTER_CARD_POOLS: Record<string, Set<string>> = {
  'CHARACTER.IRONCLAD': IRONCLAD_CARDS,
  'CHARACTER.DEFECT': DEFECT_CARDS,
  'CHARACTER.REGENT': REGENT_CARDS,
};

/**
 * Check if a card is in the character's native card pool.
 * Returns true if the card is native, false if it's a cross-character card.
 * If we don't have pool data for the character, assume all cards are native.
 */
export function isNativeCard(character: string, cardId: string): boolean {
  const pool = CHARACTER_CARD_POOLS[character];
  if (!pool) return true; // Unknown character — assume native
  return pool.has(cardId);
}

/**
 * Get all known characters
 */
export function getKnownCharacters(): string[] {
  return Object.keys(CHARACTER_CARD_POOLS);
}

/**
 * Build card pools dynamically from loaded runs.
 * Since STS2 is in early access and card pools change,
 * this supplements the hardcoded pools with observed data.
 */
export function buildDynamicCardPools(
  runs: { character: string; cardId: string }[]
): Record<string, Set<string>> {
  const pools: Record<string, Set<string>> = {};
  for (const { character, cardId } of runs) {
    if (!pools[character]) pools[character] = new Set();
    pools[character].add(cardId);
  }
  return pools;
}
