// Auto-generated from https://github.com/ptrlrd/spire-codex (v0.104.0)
// 576 cards — regenerate with: node scripts/generate-meta.mjs

export type CardColor = 'Colorless' | 'Curse' | 'Defect' | 'Event' | 'Ironclad' | 'Necrobinder' | 'Quest' | 'Regent' | 'Silent' | 'Status' | 'Token';
export type CardRarity = 'Ancient' | 'Basic' | 'Common' | 'Curse' | 'Event' | 'Quest' | 'Rare' | 'Status' | 'Token' | 'Uncommon';
export type CardType = 'Attack' | 'Curse' | 'Power' | 'Quest' | 'Skill' | 'Status';
export type CardTarget = 'AllAllies' | 'AllEnemies' | 'AnyAlly' | 'AnyEnemy' | 'None' | 'RandomEnemy' | 'Self';
export type CardKeyword = 'Eternal' | 'Ethereal' | 'Exhaust' | 'Innate' | 'Retain' | 'Sly' | 'Unplayable';
export type CardTag = 'Defend' | 'Minion' | 'OstyAttack' | 'Shiv' | 'Strike';

export interface CardMeta {
  name: string;
  color: CardColor;
  rarity: CardRarity;
  type: CardType;
  // Base energy cost. Note: -1 means "unplayable" for curses/statuses,
  // but a few X-cost cards (e.g. Cascade) also report cost=-1 — check isXCost.
  cost: number;
  // Absolute new cost when upgraded; present only when upgrading changes the cost.
  costUpgraded?: number;
  isXCost?: boolean;
  isXStarCost?: boolean;
  starCost?: number;
  target: CardTarget;
  keywords?: CardKeyword[];
  tags?: CardTag[];
  damage?: number;
  block?: number;
  hitCount?: number;
  cardsDraw?: number;
  energyGain?: number;
  hpLoss?: number;
  // Map of power_key (e.g. "Vulnerable", "Poison", "Strength") to amount applied.
  powersApplied?: Record<string, number>;
  // Card IDs spawned/added by playing this card (e.g. ["SHIV"]).
  spawnsCards?: string[];
}

const CARD_META: Record<string, CardMeta> = {
  'CARD.ABRASIVE': { name: 'Abrasive', color: 'Silent', rarity: 'Rare', type: 'Power', cost: 3, target: 'Self', keywords: ['Sly'], powersApplied: { "Thorns": 4, "Dexterity": 1 } },
  'CARD.ACCELERANT': { name: 'Accelerant', color: 'Silent', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self' },
  'CARD.ACCURACY': { name: 'Accuracy', color: 'Silent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Accuracy": 4 }, spawnsCards: ['SHIV'] },
  'CARD.ACROBATICS': { name: 'Acrobatics', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 3 },
  'CARD.ADAPTIVE_STRIKE': { name: 'Adaptive Strike', color: 'Defect', rarity: 'Rare', type: 'Attack', cost: 2, target: 'AnyEnemy', tags: ['Strike'], damage: 18 },
  'CARD.ADRENALINE': { name: 'Adrenaline', color: 'Silent', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], cardsDraw: 2, energyGain: 1 },
  'CARD.AFTERIMAGE': { name: 'Afterimage', color: 'Silent', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Afterimage": 1 } },
  'CARD.AFTERLIFE': { name: 'Afterlife', color: 'Necrobinder', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust'] },
  'CARD.AGGRESSION': { name: 'Aggression', color: 'Ironclad', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self' },
  'CARD.ALCHEMIZE': { name: 'Alchemize', color: 'Colorless', rarity: 'Rare', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self', keywords: ['Exhaust'] },
  'CARD.ALIGNMENT': { name: 'Alignment', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 0, starCost: 3, target: 'Self', energyGain: 2 },
  'CARD.ALL_FOR_ONE': { name: 'All for One', color: 'Defect', rarity: 'Rare', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 10 },
  'CARD.ANGER': { name: 'Anger', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 6 },
  'CARD.ANOINTED': { name: 'Anointed', color: 'Colorless', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust'] },
  'CARD.ANTICIPATE': { name: 'Anticipate', color: 'Silent', rarity: 'Common', type: 'Skill', cost: 0, target: 'Self', powersApplied: { "Dexterity": 2 } },
  'CARD.APOTHEOSIS': { name: 'Apotheosis', color: 'Event', rarity: 'Ancient', type: 'Skill', cost: 2, costUpgraded: 1, target: 'Self', keywords: ['Exhaust', 'Innate'] },
  'CARD.APPARITION': { name: 'Apparition', color: 'Event', rarity: 'Ancient', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust', 'Ethereal'], powersApplied: { "Intangible": 1 } },
  'CARD.ARMAMENTS': { name: 'Armaments', color: 'Ironclad', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 5 },
  'CARD.ARSENAL': { name: 'Arsenal', color: 'Regent', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Arsenal": 1 } },
  'CARD.ASCENDERS_BANE': { name: 'Ascender\'s Bane', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Ethereal', 'Unplayable', 'Eternal'] },
  'CARD.ASHEN_STRIKE': { name: 'Ashen Strike', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 6 },
  'CARD.ASSASSINATE': { name: 'Assassinate', color: 'Silent', rarity: 'Rare', type: 'Attack', cost: 0, target: 'AnyEnemy', keywords: ['Exhaust', 'Innate'], damage: 10, powersApplied: { "Vulnerable": 1 } },
  'CARD.ASTRAL_PULSE': { name: 'Astral Pulse', color: 'Regent', rarity: 'Common', type: 'Attack', cost: 0, starCost: 3, target: 'AllEnemies', damage: 14 },
  'CARD.AUTOMATION': { name: 'Automation', color: 'Colorless', rarity: 'Uncommon', type: 'Power', cost: 1, costUpgraded: 0, target: 'Self', energyGain: 1 },
  'CARD.BEGONE': { name: 'BEGONE!', color: 'Regent', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', spawnsCards: ['MINION_STRIKE'] },
  'CARD.BACKFLIP': { name: 'Backflip', color: 'Silent', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 5, cardsDraw: 2 },
  'CARD.BACKSTAB': { name: 'Backstab', color: 'Silent', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AnyEnemy', keywords: ['Exhaust', 'Innate'], damage: 11 },
  'CARD.BAD_LUCK': { name: 'Bad Luck', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Unplayable', 'Eternal'], hpLoss: 13 },
  'CARD.BALL_LIGHTNING': { name: 'Ball Lightning', color: 'Defect', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 7 },
  'CARD.BANSHEES_CRY': { name: 'Banshee\'s Cry', color: 'Necrobinder', rarity: 'Rare', type: 'Attack', cost: 9, costUpgraded: 7, target: 'AllEnemies', damage: 33, energyGain: 2 },
  'CARD.BARRAGE': { name: 'Barrage', color: 'Defect', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 5 },
  'CARD.BARRICADE': { name: 'Barricade', color: 'Ironclad', rarity: 'Rare', type: 'Power', cost: 3, costUpgraded: 2, target: 'Self' },
  'CARD.BASH': { name: 'Bash', color: 'Ironclad', rarity: 'Basic', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 8, powersApplied: { "Vulnerable": 2 } },
  'CARD.BATTLE_TRANCE': { name: 'Battle Trance', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', cardsDraw: 3 },
  'CARD.BEACON_OF_HOPE': { name: 'Beacon of Hope', color: 'Colorless', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self' },
  'CARD.BEAM_CELL': { name: 'Beam Cell', color: 'Defect', rarity: 'Common', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 3, powersApplied: { "Vulnerable": 1 } },
  'CARD.BEAT_DOWN': { name: 'Beat Down', color: 'Colorless', rarity: 'Rare', type: 'Skill', cost: 3, target: 'RandomEnemy', cardsDraw: 3 },
  'CARD.BEAT_INTO_SHAPE': { name: 'Beat into Shape', color: 'Regent', rarity: 'Rare', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 5 },
  'CARD.BECKON': { name: 'Beckon', color: 'Status', rarity: 'Status', type: 'Status', cost: 1, target: 'None', hpLoss: 6 },
  'CARD.BELIEVE_IN_YOU': { name: 'Believe in You', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'AnyAlly', energyGain: 2 },
  'CARD.BIASED_COGNITION': { name: 'Biased Cognition', color: 'Defect', rarity: 'Ancient', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Focus": 4, "BiasedCognition": 1 } },
  'CARD.BIG_BANG': { name: 'Big Bang', color: 'Regent', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], cardsDraw: 1, energyGain: 1 },
  'CARD.BLACK_HOLE': { name: 'Black Hole', color: 'Regent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "BlackHole": 3 } },
  'CARD.BLADE_DANCE': { name: 'Blade Dance', color: 'Silent', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust'], cardsDraw: 3, spawnsCards: ['SHIV'] },
  'CARD.BLADE_OF_INK': { name: 'Blade of Ink', color: 'Silent', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 2, spawnsCards: ['SHIV'] },
  'CARD.BLIGHT_STRIKE': { name: 'Blight Strike', color: 'Necrobinder', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 8 },
  'CARD.BLOOD_WALL': { name: 'Blood Wall', color: 'Ironclad', rarity: 'Common', type: 'Skill', cost: 2, target: 'Self', block: 16, hpLoss: 2 },
  'CARD.BLOODLETTING': { name: 'Bloodletting', color: 'Ironclad', rarity: 'Common', type: 'Skill', cost: 0, target: 'Self', energyGain: 2, hpLoss: 3 },
  'CARD.BLUDGEON': { name: 'Bludgeon', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 3, target: 'AnyEnemy', damage: 32 },
  'CARD.BLUR': { name: 'Blur', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', block: 5 },
  'CARD.BODY_SLAM': { name: 'Body Slam', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 1, costUpgraded: 0, target: 'AnyEnemy', damage: 0 },
  'CARD.BODYGUARD': { name: 'Bodyguard', color: 'Necrobinder', rarity: 'Basic', type: 'Skill', cost: 1, target: 'Self' },
  'CARD.BOLAS': { name: 'Bolas', color: 'Colorless', rarity: 'Rare', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 3 },
  'CARD.BOMBARDMENT': { name: 'Bombardment', color: 'Regent', rarity: 'Rare', type: 'Attack', cost: 3, target: 'AnyEnemy', keywords: ['Exhaust'], damage: 18 },
  'CARD.BONE_SHARDS': { name: 'Bone Shards', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AllEnemies', tags: ['OstyAttack'], damage: 9, block: 9 },
  'CARD.BOOST_AWAY': { name: 'Boost Away', color: 'Defect', rarity: 'Common', type: 'Skill', cost: 0, target: 'Self', block: 6, spawnsCards: ['DAZED'] },
  'CARD.BOOT_SEQUENCE': { name: 'Boot Sequence', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust', 'Innate'], block: 10 },
  'CARD.BORROWED_TIME': { name: 'Borrowed Time', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', energyGain: 4 },
  'CARD.BOUNCING_FLASK': { name: 'Bouncing Flask', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'RandomEnemy', powersApplied: { "Poison": 3 } },
  'CARD.BRAND': { name: 'Brand', color: 'Ironclad', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', hpLoss: 1, powersApplied: { "Strength": 1 } },
  'CARD.BREAK': { name: 'Break', color: 'Ironclad', rarity: 'Ancient', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 20, powersApplied: { "Vulnerable": 5 } },
  'CARD.BREAKTHROUGH': { name: 'Breakthrough', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 1, target: 'AllEnemies', damage: 9, hpLoss: 1 },
  'CARD.BRIGHTEST_FLAME': { name: 'Brightest Flame', color: 'Event', rarity: 'Ancient', type: 'Skill', cost: 0, target: 'Self', cardsDraw: 2, energyGain: 2 },
  'CARD.BUBBLE_BUBBLE': { name: 'Bubble Bubble', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AnyEnemy', powersApplied: { "Poison": 9 } },
  'CARD.BUFFER': { name: 'Buffer', color: 'Defect', rarity: 'Rare', type: 'Power', cost: 2, target: 'Self', powersApplied: { "Buffer": 1 } },
  'CARD.BULK_UP': { name: 'Bulk Up', color: 'Defect', rarity: 'Uncommon', type: 'Power', cost: 2, target: 'Self', powersApplied: { "Strength": 2, "Dexterity": 2 } },
  'CARD.BULLET_TIME': { name: 'Bullet Time', color: 'Silent', rarity: 'Rare', type: 'Skill', cost: 3, costUpgraded: 2, target: 'Self' },
  'CARD.BULLY': { name: 'Bully', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 4 },
  'CARD.BULWARK': { name: 'Bulwark', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'Self', block: 13 },
  'CARD.BUNDLE_OF_JOY': { name: 'Bundle of Joy', color: 'Regent', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust'], cardsDraw: 3 },
  'CARD.BURN': { name: 'Burn', color: 'Status', rarity: 'Status', type: 'Status', cost: -1, target: 'None', keywords: ['Unplayable'], damage: 2 },
  'CARD.BURNING_PACT': { name: 'Burning Pact', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 2 },
  'CARD.BURST': { name: 'Burst', color: 'Silent', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self' },
  'CARD.BURY': { name: 'Bury', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack', cost: 4, target: 'AnyEnemy', damage: 52 },
  'CARD.BYRD_SWOOP': { name: 'Byrd Swoop', color: 'Event', rarity: 'Event', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 14 },
  'CARD.BYRDONIS_EGG': { name: 'Byrdonis Egg', color: 'Quest', rarity: 'Quest', type: 'Quest', cost: -1, target: 'None', keywords: ['Unplayable'] },
  'CARD.CHARGE': { name: 'CHARGE!!', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 2, spawnsCards: ['MINION_DIVE_BOMB'] },
  'CARD.CALAMITY': { name: 'Calamity', color: 'Colorless', rarity: 'Rare', type: 'Power', cost: 3, costUpgraded: 2, target: 'Self' },
  'CARD.CALCIFY': { name: 'Calcify', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Calcify": 4 } },
  'CARD.CALCULATED_GAMBLE': { name: 'Calculated Gamble', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'] },
  'CARD.CALL_OF_THE_VOID': { name: 'Call of the Void', color: 'Necrobinder', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self', cardsDraw: 1 },
  'CARD.CALTROPS': { name: 'Caltrops', color: 'Event', rarity: 'Event', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Thorns": 3 } },
  'CARD.CAPACITOR': { name: 'Capacitor', color: 'Defect', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self' },
  'CARD.CAPTURE_SPIRIT': { name: 'Capture Spirit', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AnyEnemy', damage: 3, cardsDraw: 3, spawnsCards: ['SOUL'] },
  'CARD.CASCADE': { name: 'Cascade', color: 'Ironclad', rarity: 'Rare', type: 'Skill', cost: -1, isXCost: true, target: 'Self' },
  'CARD.CATASTROPHE': { name: 'Catastrophe', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'Self', cardsDraw: 2 },
  'CARD.CELESTIAL_MIGHT': { name: 'Celestial Might', color: 'Regent', rarity: 'Common', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 6, hitCount: 3 },
  'CARD.CHAOS': { name: 'Chaos', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self' },
  'CARD.CHARGE_BATTERY': { name: 'Charge Battery', color: 'Defect', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 7, energyGain: 1 },
  'CARD.CHILD_OF_THE_STARS': { name: 'Child of the Stars', color: 'Regent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self' },
  'CARD.CHILL': { name: 'Chill', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'] },
  'CARD.CINDER': { name: 'Cinder', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 18 },
  'CARD.CLASH': { name: 'Clash', color: 'Event', rarity: 'Event', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 14 },
  'CARD.CLAW': { name: 'Claw', color: 'Defect', rarity: 'Common', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 3 },
  'CARD.CLEANSE': { name: 'Cleanse', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self' },
  'CARD.CLOAK_AND_DAGGER': { name: 'Cloak and Dagger', color: 'Silent', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 6, cardsDraw: 1, spawnsCards: ['SHIV'] },
  'CARD.CLOAK_OF_STARS': { name: 'Cloak of Stars', color: 'Regent', rarity: 'Common', type: 'Skill', cost: 0, starCost: 1, target: 'Self', block: 7 },
  'CARD.CLUMSY': { name: 'Clumsy', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Ethereal', 'Unplayable'] },
  'CARD.COLD_SNAP': { name: 'Cold Snap', color: 'Defect', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 6 },
  'CARD.COLLISION_COURSE': { name: 'Collision Course', color: 'Regent', rarity: 'Common', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 11, spawnsCards: ['DEBRIS'] },
  'CARD.COLOSSUS': { name: 'Colossus', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', block: 5 },
  'CARD.COMET': { name: 'Comet', color: 'Regent', rarity: 'Rare', type: 'Attack', cost: 0, starCost: 5, target: 'AnyEnemy', damage: 33, powersApplied: { "Vulnerable": 3, "Weak": 3 } },
  'CARD.COMPACT': { name: 'Compact', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', block: 6, spawnsCards: ['FUEL'] },
  'CARD.COMPILE_DRIVER': { name: 'Compile Driver', color: 'Defect', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 7 },
  'CARD.CONFLAGRATION': { name: 'Conflagration', color: 'Ironclad', rarity: 'Rare', type: 'Attack', cost: 1, target: 'AllEnemies', damage: 2, hitCount: 4 },
  'CARD.CONQUEROR': { name: 'Conqueror', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AnyEnemy' },
  'CARD.CONSUMING_SHADOW': { name: 'Consuming Shadow', color: 'Defect', rarity: 'Rare', type: 'Power', cost: 2, target: 'Self', powersApplied: { "ConsumingShadow": 1 } },
  'CARD.CONVERGENCE': { name: 'Convergence', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', energyGain: 1 },
  'CARD.COOLANT': { name: 'Coolant', color: 'Defect', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Coolant": 2 } },
  'CARD.COOLHEADED': { name: 'Coolheaded', color: 'Defect', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 1 },
  'CARD.COORDINATE': { name: 'Coordinate', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AnyAlly', powersApplied: { "Strength": 5 } },
  'CARD.CORROSIVE_WAVE': { name: 'Corrosive Wave', color: 'Silent', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self' },
  'CARD.CORRUPTION': { name: 'Corruption', color: 'Ironclad', rarity: 'Ancient', type: 'Power', cost: 3, costUpgraded: 2, target: 'Self' },
  'CARD.COSMIC_INDIFFERENCE': { name: 'Cosmic Indifference', color: 'Regent', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 6 },
  'CARD.COUNTDOWN': { name: 'Countdown', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Countdown": 6 } },
  'CARD.CRASH_LANDING': { name: 'Crash Landing', color: 'Regent', rarity: 'Rare', type: 'Attack', cost: 1, target: 'AllEnemies', damage: 21, spawnsCards: ['DEBRIS'] },
  'CARD.CREATIVE_AI': { name: 'Creative AI', color: 'Defect', rarity: 'Rare', type: 'Power', cost: 3, costUpgraded: 2, target: 'Self' },
  'CARD.CRESCENT_SPEAR': { name: 'Crescent Spear', color: 'Regent', rarity: 'Common', type: 'Attack', cost: 1, starCost: 1, target: 'AnyEnemy', damage: 6 },
  'CARD.CRIMSON_MANTLE': { name: 'Crimson Mantle', color: 'Ironclad', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self', powersApplied: { "CrimsonMantle": 8 } },
  'CARD.CRUELTY': { name: 'Cruelty', color: 'Ironclad', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Cruelty": 25 } },
  'CARD.CRUSH_UNDER': { name: 'Crush Under', color: 'Regent', rarity: 'Common', type: 'Attack', cost: 1, target: 'AllEnemies', damage: 7 },
  'CARD.CURSE_OF_THE_BELL': { name: 'Curse of the Bell', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Unplayable', 'Eternal'] },
  'CARD.DAGGER_SPRAY': { name: 'Dagger Spray', color: 'Silent', rarity: 'Common', type: 'Attack', cost: 1, target: 'AllEnemies', damage: 4, hitCount: 2 },
  'CARD.DAGGER_THROW': { name: 'Dagger Throw', color: 'Silent', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 9 },
  'CARD.DANSE_MACABRE': { name: 'Danse Macabre', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', energyGain: 2, powersApplied: { "DanseMacabre": 4 } },
  'CARD.DARK_EMBRACE': { name: 'Dark Embrace', color: 'Ironclad', rarity: 'Rare', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self' },
  'CARD.DARK_SHACKLES': { name: 'Dark Shackles', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'AnyEnemy', keywords: ['Exhaust'] },
  'CARD.DARKNESS': { name: 'Darkness', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self' },
  'CARD.DASH': { name: 'Dash', color: 'Silent', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 10, block: 10 },
  'CARD.DAZED': { name: 'Dazed', color: 'Status', rarity: 'Status', type: 'Status', cost: -1, target: 'None', keywords: ['Ethereal', 'Unplayable'] },
  'CARD.DEADLY_POISON': { name: 'Deadly Poison', color: 'Silent', rarity: 'Common', type: 'Skill', cost: 1, target: 'AnyEnemy', powersApplied: { "Poison": 5 } },
  'CARD.DEATH_MARCH': { name: 'Death March', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 8 },
  'CARD.DEATHS_DOOR': { name: 'Death\'s Door', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', block: 6 },
  'CARD.DEATHBRINGER': { name: 'Deathbringer', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'AllEnemies', powersApplied: { "Doom": 21, "Weak": 1 } },
  'CARD.DEBILITATE': { name: 'Debilitate', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 10, powersApplied: { "Debilitate": 3 } },
  'CARD.DEBRIS': { name: 'Debris', color: 'Status', rarity: 'Status', type: 'Status', cost: 1, target: 'None', keywords: ['Exhaust'] },
  'CARD.DEBT': { name: 'Debt', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Unplayable'] },
  'CARD.DECAY': { name: 'Decay', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Unplayable'], damage: 2 },
  'CARD.DECISIONS_DECISIONS': { name: 'Decisions, Decisions', color: 'Regent', rarity: 'Rare', type: 'Skill', cost: 0, starCost: 6, target: 'Self', keywords: ['Exhaust'], cardsDraw: 3 },
  'CARD.DEFEND_IRONCLAD': { name: 'Defend', color: 'Ironclad', rarity: 'Basic', type: 'Skill', cost: 1, target: 'Self', tags: ['Defend'], block: 5 },
  'CARD.DEFEND_SILENT': { name: 'Defend', color: 'Silent', rarity: 'Basic', type: 'Skill', cost: 1, target: 'Self', tags: ['Defend'], block: 5 },
  'CARD.DEFEND_REGENT': { name: 'Defend', color: 'Regent', rarity: 'Basic', type: 'Skill', cost: 1, target: 'Self', tags: ['Defend'], block: 5 },
  'CARD.DEFEND_NECROBINDER': { name: 'Defend', color: 'Necrobinder', rarity: 'Basic', type: 'Skill', cost: 1, target: 'Self', tags: ['Defend'], block: 5 },
  'CARD.DEFEND_DEFECT': { name: 'Defend', color: 'Defect', rarity: 'Basic', type: 'Skill', cost: 1, target: 'Self', tags: ['Defend'], block: 5 },
  'CARD.DEFILE': { name: 'Defile', color: 'Necrobinder', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', keywords: ['Ethereal'], damage: 13 },
  'CARD.DEFLECT': { name: 'Deflect', color: 'Silent', rarity: 'Common', type: 'Skill', cost: 0, target: 'Self', block: 4 },
  'CARD.DEFRAGMENT': { name: 'Defragment', color: 'Defect', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Focus": 1 } },
  'CARD.DEFY': { name: 'Defy', color: 'Necrobinder', rarity: 'Common', type: 'Skill', cost: 1, target: 'AnyEnemy', keywords: ['Ethereal'], block: 6, powersApplied: { "Weak": 1 } },
  'CARD.DELAY': { name: 'Delay', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'Self', block: 11, energyGain: 1 },
  'CARD.DEMESNE': { name: 'Demesne', color: 'Necrobinder', rarity: 'Rare', type: 'Power', cost: 3, costUpgraded: 2, target: 'Self', keywords: ['Ethereal'], cardsDraw: 1, energyGain: 1 },
  'CARD.DEMON_FORM': { name: 'Demon Form', color: 'Ironclad', rarity: 'Rare', type: 'Power', cost: 3, target: 'Self', powersApplied: { "Strength": 2 } },
  'CARD.DEMONIC_SHIELD': { name: 'Demonic Shield', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'AnyAlly', keywords: ['Exhaust'], damage: 0, hpLoss: 1 },
  'CARD.DEVASTATE': { name: 'Devastate', color: 'Regent', rarity: 'Uncommon', type: 'Attack', cost: 1, starCost: 4, target: 'AnyEnemy', damage: 30 },
  'CARD.DEVOUR_LIFE': { name: 'Devour Life', color: 'Necrobinder', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self', powersApplied: { "DevourLife": 1 }, spawnsCards: ['SOUL'] },
  'CARD.DIRGE': { name: 'Dirge', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 0, isXCost: true, target: 'Self', keywords: ['Exhaust'], spawnsCards: ['SOUL'] },
  'CARD.DISCOVERY': { name: 'Discovery', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust'] },
  'CARD.DISINTEGRATION': { name: 'Disintegration', color: 'Token', rarity: 'Status', type: 'Status', cost: -1, target: 'None', powersApplied: { "Disintegration": 6 } },
  'CARD.DISMANTLE': { name: 'Dismantle', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 8 },
  'CARD.DISTRACTION': { name: 'Distraction', color: 'Event', rarity: 'Event', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self', keywords: ['Exhaust'] },
  'CARD.DODGE_AND_ROLL': { name: 'Dodge and Roll', color: 'Silent', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 4 },
  'CARD.DOMINATE': { name: 'Dominate', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AnyEnemy', keywords: ['Exhaust'], powersApplied: { "Vulnerable": 1 } },
  'CARD.DOUBLE_ENERGY': { name: 'Double Energy', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self', keywords: ['Exhaust'] },
  'CARD.DOUBT': { name: 'Doubt', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Unplayable'], powersApplied: { "Weak": 1 } },
  'CARD.DRAIN_POWER': { name: 'Drain Power', color: 'Necrobinder', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 10, cardsDraw: 2 },
  'CARD.DRAMATIC_ENTRANCE': { name: 'Dramatic Entrance', color: 'Colorless', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AllEnemies', keywords: ['Exhaust', 'Innate'], damage: 11 },
  'CARD.DREDGE': { name: 'Dredge', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust'], cardsDraw: 3 },
  'CARD.DRUM_OF_BATTLE': { name: 'Drum of Battle', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 2, energyGain: 2 },
  'CARD.DUAL_WIELD': { name: 'Dual Wield', color: 'Event', rarity: 'Event', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 1 },
  'CARD.DUALCAST': { name: 'Dualcast', color: 'Defect', rarity: 'Basic', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self' },
  'CARD.DYING_STAR': { name: 'Dying Star', color: 'Regent', rarity: 'Rare', type: 'Attack', cost: 1, starCost: 3, target: 'AllEnemies', keywords: ['Ethereal'], damage: 9 },
  'CARD.ECHO_FORM': { name: 'Echo Form', color: 'Defect', rarity: 'Rare', type: 'Power', cost: 3, target: 'Self', keywords: ['Ethereal'] },
  'CARD.ECHOING_SLASH': { name: 'Echoing Slash', color: 'Silent', rarity: 'Rare', type: 'Attack', cost: 1, target: 'AllEnemies', damage: 10 },
  'CARD.EIDOLON': { name: 'Eidolon', color: 'Necrobinder', rarity: 'Rare', type: 'Skill', cost: 2, costUpgraded: 1, target: 'Self' },
  'CARD.END_OF_DAYS': { name: 'End of Days', color: 'Necrobinder', rarity: 'Rare', type: 'Skill', cost: 3, target: 'AllEnemies', powersApplied: { "Doom": 29 } },
  'CARD.ENERGY_SURGE': { name: 'Energy Surge', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AllAllies', keywords: ['Exhaust'], energyGain: 2 },
  'CARD.ENFEEBLING_TOUCH': { name: 'Enfeebling Touch', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AnyEnemy', keywords: ['Ethereal'] },
  'CARD.ENLIGHTENMENT': { name: 'Enlightenment', color: 'Event', rarity: 'Event', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'] },
  'CARD.ENTHRALLED': { name: 'Enthralled', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: 2, target: 'None', keywords: ['Eternal'] },
  'CARD.ENTRENCH': { name: 'Entrench', color: 'Event', rarity: 'Event', type: 'Skill', cost: 2, costUpgraded: 1, target: 'Self' },
  'CARD.ENTROPY': { name: 'Entropy', color: 'Colorless', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self', cardsDraw: 1 },
  'CARD.ENVENOM': { name: 'Envenom', color: 'Silent', rarity: 'Rare', type: 'Power', cost: 2, target: 'Self', powersApplied: { "Envenom": 1 } },
  'CARD.EQUILIBRIUM': { name: 'Equilibrium', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'Self', block: 13 },
  'CARD.ERADICATE': { name: 'Eradicate', color: 'Necrobinder', rarity: 'Rare', type: 'Attack', cost: 0, isXCost: true, target: 'AnyEnemy', keywords: ['Retain'], damage: 11 },
  'CARD.ESCAPE_PLAN': { name: 'Escape Plan', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', block: 3 },
  'CARD.ETERNAL_ARMOR': { name: 'Eternal Armor', color: 'Colorless', rarity: 'Rare', type: 'Power', cost: 3, target: 'Self', powersApplied: { "Plating": 9 } },
  'CARD.EVIL_EYE': { name: 'Evil Eye', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', block: 8 },
  'CARD.EXPECT_A_FIGHT': { name: 'Expect a Fight', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 2, costUpgraded: 1, target: 'Self', damage: 0, energyGain: 0 },
  'CARD.EXPERTISE': { name: 'Expertise', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 6 },
  'CARD.EXPOSE': { name: 'Expose', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'AnyEnemy', keywords: ['Exhaust'] },
  'CARD.EXTERMINATE': { name: 'Exterminate', color: 'Event', rarity: 'Event', type: 'Attack', cost: 1, target: 'AllEnemies', damage: 3, hitCount: 4 },
  'CARD.FTL': { name: 'FTL', color: 'Defect', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 5, cardsDraw: 1 },
  'CARD.FALLING_STAR': { name: 'Falling Star', color: 'Regent', rarity: 'Basic', type: 'Attack', cost: 0, starCost: 2, target: 'AnyEnemy', damage: 8, powersApplied: { "Vulnerable": 1, "Weak": 1 } },
  'CARD.FAN_OF_KNIVES': { name: 'Fan of Knives', color: 'Silent', rarity: 'Rare', type: 'Power', cost: 2, target: 'Self', spawnsCards: ['SHIV'] },
  'CARD.FASTEN': { name: 'Fasten', color: 'Colorless', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', tags: ['Defend'] },
  'CARD.FEAR': { name: 'Fear', color: 'Necrobinder', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', keywords: ['Ethereal'], damage: 7, powersApplied: { "Vulnerable": 1 } },
  'CARD.FEED': { name: 'Feed', color: 'Ironclad', rarity: 'Rare', type: 'Attack', cost: 1, target: 'AnyEnemy', keywords: ['Exhaust'], damage: 10 },
  'CARD.FEEDING_FRENZY': { name: 'Feeding Frenzy', color: 'Event', rarity: 'Event', type: 'Skill', cost: 0, target: 'Self', powersApplied: { "Strength": 5 } },
  'CARD.FEEL_NO_PAIN': { name: 'Feel No Pain', color: 'Ironclad', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self' },
  'CARD.FERAL': { name: 'Feral', color: 'Defect', rarity: 'Uncommon', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self', powersApplied: { "Feral": 1 } },
  'CARD.FETCH': { name: 'Fetch', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AnyEnemy', tags: ['OstyAttack'], damage: 3, cardsDraw: 1 },
  'CARD.FIEND_FIRE': { name: 'Fiend Fire', color: 'Ironclad', rarity: 'Rare', type: 'Attack', cost: 2, target: 'AnyEnemy', keywords: ['Exhaust'], damage: 7 },
  'CARD.FIGHT_ME': { name: 'Fight Me!', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 5, hitCount: 2, powersApplied: { "Strength": 3 } },
  'CARD.FIGHT_THROUGH': { name: 'Fight Through', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', block: 13, spawnsCards: ['WOUND'] },
  'CARD.FINESSE': { name: 'Finesse', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', block: 4, cardsDraw: 1 },
  'CARD.FINISHER': { name: 'Finisher', color: 'Silent', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 6 },
  'CARD.FISTICUFFS': { name: 'Fisticuffs', color: 'Colorless', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 7 },
  'CARD.FLAK_CANNON': { name: 'Flak Cannon', color: 'Defect', rarity: 'Rare', type: 'Attack', cost: 2, target: 'RandomEnemy', damage: 8 },
  'CARD.FLAME_BARRIER': { name: 'Flame Barrier', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'Self', block: 12 },
  'CARD.FLANKING': { name: 'Flanking', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 2, costUpgraded: 1, target: 'AnyEnemy' },
  'CARD.FLASH_OF_STEEL': { name: 'Flash of Steel', color: 'Colorless', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 5, cardsDraw: 1 },
  'CARD.FLATTEN': { name: 'Flatten', color: 'Necrobinder', rarity: 'Common', type: 'Attack', cost: 2, target: 'AnyEnemy', tags: ['OstyAttack'], damage: 12 },
  'CARD.FLECHETTES': { name: 'Flechettes', color: 'Silent', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 5 },
  'CARD.FLICK_FLACK': { name: 'Flick-Flack', color: 'Silent', rarity: 'Common', type: 'Attack', cost: 1, target: 'AllEnemies', keywords: ['Sly'], damage: 6 },
  'CARD.FOCUSED_STRIKE': { name: 'Focused Strike', color: 'Defect', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 9, powersApplied: { "Focus": 1 } },
  'CARD.FOLLOW_THROUGH': { name: 'Follow Through', color: 'Silent', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 7 },
  'CARD.FOLLY': { name: 'Folly', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Innate', 'Ethereal', 'Unplayable', 'Eternal'] },
  'CARD.FOOTWORK': { name: 'Footwork', color: 'Silent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Dexterity": 2 } },
  'CARD.FORBIDDEN_GRIMOIRE': { name: 'Forbidden Grimoire', color: 'Necrobinder', rarity: 'Ancient', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self', keywords: ['Eternal'] },
  'CARD.FOREGONE_CONCLUSION': { name: 'Foregone Conclusion', color: 'Regent', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 2 },
  'CARD.FORGOTTEN_RITUAL': { name: 'Forgotten Ritual', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust'], energyGain: 3 },
  'CARD.FRANTIC_ESCAPE': { name: 'Frantic Escape', color: 'Status', rarity: 'Status', type: 'Status', cost: 1, target: 'Self' },
  'CARD.FRIENDSHIP': { name: 'Friendship', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', energyGain: 1, powersApplied: { "Strength": 2 } },
  'CARD.FUEL': { name: 'Fuel', color: 'Token', rarity: 'Token', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], cardsDraw: 1, energyGain: 1 },
  'CARD.FURNACE': { name: 'Furnace', color: 'Regent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self' },
  'CARD.FUSION': { name: 'Fusion', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 2, costUpgraded: 1, target: 'Self' },
  'CARD.GUARDS': { name: 'GUARDS!!!', color: 'Regent', rarity: 'Rare', type: 'Skill', cost: 2, target: 'Self', keywords: ['Exhaust'], spawnsCards: ['MINION_SACRIFICE'] },
  'CARD.GAMMA_BLAST': { name: 'Gamma Blast', color: 'Regent', rarity: 'Uncommon', type: 'Attack', cost: 0, starCost: 3, target: 'AnyEnemy', damage: 13, powersApplied: { "Vulnerable": 2, "Weak": 2 } },
  'CARD.GANG_UP': { name: 'Gang Up', color: 'Colorless', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 5 },
  'CARD.GATHER_LIGHT': { name: 'Gather Light', color: 'Regent', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 8 },
  'CARD.GENESIS': { name: 'Genesis', color: 'Regent', rarity: 'Rare', type: 'Power', cost: 2, target: 'Self' },
  'CARD.GENETIC_ALGORITHM': { name: 'Genetic Algorithm', color: 'Defect', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust'], block: 1 },
  'CARD.GIANT_ROCK': { name: 'Giant Rock', color: 'Token', rarity: 'Token', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 16 },
  'CARD.GLACIER': { name: 'Glacier', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'Self', block: 6 },
  'CARD.GLASSWORK': { name: 'Glasswork', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', block: 5 },
  'CARD.GLIMMER': { name: 'Glimmer', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 3 },
  'CARD.GLIMPSE_BEYOND': { name: 'Glimpse Beyond', color: 'Necrobinder', rarity: 'Rare', type: 'Skill', cost: 1, target: 'AllAllies', keywords: ['Exhaust'], cardsDraw: 3, spawnsCards: ['SOUL'] },
  'CARD.GLITTERSTREAM': { name: 'Glitterstream', color: 'Regent', rarity: 'Common', type: 'Skill', cost: 2, target: 'Self', block: 11 },
  'CARD.GLOW': { name: 'Glow', color: 'Regent', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 1 },
  'CARD.GO_FOR_THE_EYES': { name: 'Go for the Eyes', color: 'Defect', rarity: 'Common', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 3, powersApplied: { "Weak": 1 } },
  'CARD.GOLD_AXE': { name: 'Gold Axe', color: 'Colorless', rarity: 'Rare', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 0 },
  'CARD.GRAND_FINALE': { name: 'Grand Finale', color: 'Silent', rarity: 'Rare', type: 'Attack', cost: 0, target: 'AllEnemies', damage: 60 },
  'CARD.GRAVE_WARDEN': { name: 'Grave Warden', color: 'Necrobinder', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 8, cardsDraw: 1, spawnsCards: ['SOUL'] },
  'CARD.GRAVEBLAST': { name: 'Graveblast', color: 'Necrobinder', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', keywords: ['Exhaust'], damage: 4 },
  'CARD.GREED': { name: 'Greed', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Unplayable', 'Eternal'] },
  'CARD.GUIDING_STAR': { name: 'Guiding Star', color: 'Regent', rarity: 'Common', type: 'Attack', cost: 1, starCost: 2, target: 'AnyEnemy', damage: 12, cardsDraw: 2 },
  'CARD.GUILTY': { name: 'Guilty', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Unplayable'] },
  'CARD.GUNK_UP': { name: 'Gunk Up', color: 'Defect', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 4, hitCount: 3, spawnsCards: ['SLIMED'] },
  'CARD.HAILSTORM': { name: 'Hailstorm', color: 'Defect', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Hailstorm": 6 } },
  'CARD.HAMMER_TIME': { name: 'Hammer Time', color: 'Regent', rarity: 'Rare', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self' },
  'CARD.HAND_TRICK': { name: 'Hand Trick', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', block: 7 },
  'CARD.HAND_OF_GREED': { name: 'Hand of Greed', color: 'Colorless', rarity: 'Rare', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 20 },
  'CARD.HANG': { name: 'Hang', color: 'Necrobinder', rarity: 'Rare', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 10 },
  'CARD.HAUNT': { name: 'Haunt', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', hpLoss: 6, spawnsCards: ['SOUL'] },
  'CARD.HAVOC': { name: 'Havoc', color: 'Ironclad', rarity: 'Common', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self' },
  'CARD.HAZE': { name: 'Haze', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 3, target: 'AllEnemies', keywords: ['Sly'], powersApplied: { "Poison": 4 } },
  'CARD.HEADBUTT': { name: 'Headbutt', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 9 },
  'CARD.HEAVENLY_DRILL': { name: 'Heavenly Drill', color: 'Regent', rarity: 'Rare', type: 'Attack', cost: 0, isXCost: true, target: 'AnyEnemy', damage: 8, energyGain: 4 },
  'CARD.HEGEMONY': { name: 'Hegemony', color: 'Regent', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 15, energyGain: 2 },
  'CARD.HEIRLOOM_HAMMER': { name: 'Heirloom Hammer', color: 'Regent', rarity: 'Rare', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 20 },
  'CARD.HELIX_DRILL': { name: 'Helix Drill', color: 'Defect', rarity: 'Rare', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 3 },
  'CARD.HELLO_WORLD': { name: 'Hello World', color: 'Event', rarity: 'Event', type: 'Power', cost: 1, target: 'Self' },
  'CARD.HELLRAISER': { name: 'Hellraiser', color: 'Ironclad', rarity: 'Rare', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self' },
  'CARD.HEMOKINESIS': { name: 'Hemokinesis', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 15, hpLoss: 2 },
  'CARD.HIDDEN_CACHE': { name: 'Hidden Cache', color: 'Regent', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', powersApplied: { "StarNextTurn": 3 } },
  'CARD.HIDDEN_DAGGERS': { name: 'Hidden Daggers', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', cardsDraw: 2, spawnsCards: ['SHIV'] },
  'CARD.HIDDEN_GEM': { name: 'Hidden Gem', color: 'Colorless', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self' },
  'CARD.HIGH_FIVE': { name: 'High Five', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AllEnemies', tags: ['OstyAttack'], damage: 11, powersApplied: { "Vulnerable": 2 } },
  'CARD.HOLOGRAM': { name: 'Hologram', color: 'Defect', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust'], block: 3 },
  'CARD.HOTFIX': { name: 'Hotfix', color: 'Defect', rarity: 'Common', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], powersApplied: { "Focus": 2 } },
  'CARD.HOWL_FROM_BEYOND': { name: 'Howl from Beyond', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 3, target: 'AllEnemies', damage: 16 },
  'CARD.HUDDLE_UP': { name: 'Huddle Up', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AllAllies', keywords: ['Exhaust'], cardsDraw: 2 },
  'CARD.HYPERBEAM': { name: 'Hyperbeam', color: 'Defect', rarity: 'Rare', type: 'Attack', cost: 2, target: 'AllEnemies', damage: 26, powersApplied: { "Focus": 3 } },
  'CARD.I_AM_INVINCIBLE': { name: 'I Am Invincible', color: 'Regent', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self', block: 10 },
  'CARD.ICE_LANCE': { name: 'Ice Lance', color: 'Defect', rarity: 'Rare', type: 'Attack', cost: 3, target: 'AnyEnemy', damage: 19 },
  'CARD.IGNITION': { name: 'Ignition', color: 'Defect', rarity: 'Rare', type: 'Skill', cost: 1, target: 'AnyAlly', keywords: ['Exhaust'] },
  'CARD.IMPATIENCE': { name: 'Impatience', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', cardsDraw: 2 },
  'CARD.IMPERVIOUS': { name: 'Impervious', color: 'Ironclad', rarity: 'Rare', type: 'Skill', cost: 2, target: 'Self', keywords: ['Exhaust'], block: 30 },
  'CARD.INFECTION': { name: 'Infection', color: 'Status', rarity: 'Status', type: 'Status', cost: -1, target: 'None', keywords: ['Unplayable'], damage: 3 },
  'CARD.INFERNAL_BLADE': { name: 'Infernal Blade', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self', keywords: ['Exhaust'] },
  'CARD.INFERNO': { name: 'Inferno', color: 'Ironclad', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Inferno": 6 } },
  'CARD.INFINITE_BLADES': { name: 'Infinite Blades', color: 'Silent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', spawnsCards: ['SHIV'] },
  'CARD.INFLAME': { name: 'Inflame', color: 'Ironclad', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Strength": 2 } },
  'CARD.INJURY': { name: 'Injury', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Unplayable'] },
  'CARD.INTERCEPT': { name: 'Intercept', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AnyAlly', block: 9 },
  'CARD.INVOKE': { name: 'Invoke', color: 'Necrobinder', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', energyGain: 2 },
  'CARD.IRON_WAVE': { name: 'Iron Wave', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 5, block: 5 },
  'CARD.ITERATION': { name: 'Iteration', color: 'Defect', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Iteration": 2 } },
  'CARD.JACK_OF_ALL_TRADES': { name: 'Jack of All Trades', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], cardsDraw: 1 },
  'CARD.JACKPOT': { name: 'Jackpot', color: 'Colorless', rarity: 'Rare', type: 'Attack', cost: 3, target: 'AnyEnemy', damage: 25, cardsDraw: 3 },
  'CARD.JUGGERNAUT': { name: 'Juggernaut', color: 'Ironclad', rarity: 'Rare', type: 'Power', cost: 2, target: 'Self', powersApplied: { "Juggernaut": 5 } },
  'CARD.JUGGLING': { name: 'Juggling', color: 'Ironclad', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self' },
  'CARD.KINGLY_KICK': { name: 'Kingly Kick', color: 'Regent', rarity: 'Uncommon', type: 'Attack', cost: 4, target: 'AnyEnemy', damage: 27 },
  'CARD.KINGLY_PUNCH': { name: 'Kingly Punch', color: 'Regent', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 8 },
  'CARD.KNIFE_TRAP': { name: 'Knife Trap', color: 'Silent', rarity: 'Rare', type: 'Skill', cost: 2, target: 'AnyEnemy', tags: ['Shiv'], damage: 0, spawnsCards: ['SHIV'] },
  'CARD.KNOCKDOWN': { name: 'Knockdown', color: 'Colorless', rarity: 'Rare', type: 'Attack', cost: 3, target: 'AnyEnemy', damage: 10, powersApplied: { "Knockdown": 2 } },
  'CARD.KNOCKOUT_BLOW': { name: 'Knockout Blow', color: 'Regent', rarity: 'Uncommon', type: 'Attack', cost: 3, target: 'AnyEnemy', damage: 30 },
  'CARD.KNOW_THY_PLACE': { name: 'Know Thy Place', color: 'Regent', rarity: 'Common', type: 'Skill', cost: 0, target: 'AnyEnemy', keywords: ['Exhaust'], powersApplied: { "Weak": 1, "Vulnerable": 1 } },
  'CARD.LANTERN_KEY': { name: 'Lantern Key', color: 'Quest', rarity: 'Quest', type: 'Quest', cost: -1, target: 'Self', keywords: ['Unplayable'] },
  'CARD.LARGESSE': { name: 'Largesse', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'AnyAlly' },
  'CARD.LEADING_STRIKE': { name: 'Leading Strike', color: 'Silent', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 3, spawnsCards: ['SHIV'] },
  'CARD.LEAP': { name: 'Leap', color: 'Defect', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 9 },
  'CARD.LEG_SWEEP': { name: 'Leg Sweep', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'AnyEnemy', block: 11, powersApplied: { "Weak": 2 } },
  'CARD.LEGION_OF_BONE': { name: 'Legion of Bone', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'AllAllies', keywords: ['Exhaust'] },
  'CARD.LETHALITY': { name: 'Lethality', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', keywords: ['Ethereal'], powersApplied: { "Lethality": 50 } },
  'CARD.LIFT': { name: 'Lift', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AnyAlly', block: 11 },
  'CARD.LIGHTNING_ROD': { name: 'Lightning Rod', color: 'Defect', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 4, powersApplied: { "LightningRod": 2 } },
  'CARD.LOOP': { name: 'Loop', color: 'Defect', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self' },
  'CARD.LUMINESCE': { name: 'Luminesce', color: 'Token', rarity: 'Token', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust', 'Retain'], energyGain: 2 },
  'CARD.LUNAR_BLAST': { name: 'Lunar Blast', color: 'Regent', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 4 },
  'CARD.MACHINE_LEARNING': { name: 'Machine Learning', color: 'Defect', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self', cardsDraw: 1 },
  'CARD.MAD_SCIENCE': { name: 'Mad Science', color: 'Event', rarity: 'Event', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 12, block: 8 },
  'CARD.MAKE_IT_SO': { name: 'Make It So', color: 'Regent', rarity: 'Rare', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 6, cardsDraw: 3 },
  'CARD.MALAISE': { name: 'Malaise', color: 'Silent', rarity: 'Rare', type: 'Skill', cost: 0, isXCost: true, target: 'AnyEnemy', keywords: ['Exhaust'] },
  'CARD.MANGLE': { name: 'Mangle', color: 'Ironclad', rarity: 'Rare', type: 'Attack', cost: 3, target: 'AnyEnemy', damage: 15 },
  'CARD.MANIFEST_AUTHORITY': { name: 'Manifest Authority', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', block: 7 },
  'CARD.MASTER_PLANNER': { name: 'Master Planner', color: 'Silent', rarity: 'Rare', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self' },
  'CARD.MASTER_OF_STRATEGY': { name: 'Master of Strategy', color: 'Colorless', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], cardsDraw: 3 },
  'CARD.MAUL': { name: 'Maul', color: 'Event', rarity: 'Ancient', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 5, hitCount: 2 },
  'CARD.MAYHEM': { name: 'Mayhem', color: 'Colorless', rarity: 'Rare', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self' },
  'CARD.MELANCHOLY': { name: 'Melancholy', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 3, target: 'Self', block: 13, energyGain: 1 },
  'CARD.MEMENTO_MORI': { name: 'Memento Mori', color: 'Silent', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 9 },
  'CARD.METAMORPHOSIS': { name: 'Metamorphosis', color: 'Event', rarity: 'Event', type: 'Skill', cost: 2, target: 'Self', keywords: ['Exhaust'], cardsDraw: 3 },
  'CARD.METEOR_SHOWER': { name: 'Meteor Shower', color: 'Regent', rarity: 'Ancient', type: 'Attack', cost: 0, starCost: 2, target: 'AllEnemies', damage: 14, powersApplied: { "Vulnerable": 2, "Weak": 2 } },
  'CARD.METEOR_STRIKE': { name: 'Meteor Strike', color: 'Defect', rarity: 'Rare', type: 'Attack', cost: 5, target: 'AnyEnemy', tags: ['Strike'], damage: 24 },
  'CARD.MIMIC': { name: 'Mimic', color: 'Colorless', rarity: 'Rare', type: 'Skill', cost: 1, target: 'AnyAlly', keywords: ['Exhaust'], damage: 0 },
  'CARD.MIND_BLAST': { name: 'Mind Blast', color: 'Colorless', rarity: 'Uncommon', type: 'Attack', cost: 1, costUpgraded: 0, target: 'AnyEnemy', keywords: ['Innate'], damage: 0 },
  'CARD.MIND_ROT': { name: 'Mind Rot', color: 'Token', rarity: 'Status', type: 'Status', cost: -1, target: 'None', powersApplied: { "MindRot": 1 } },
  'CARD.MINION_DIVE_BOMB': { name: 'Minion Dive Bomb', color: 'Token', rarity: 'Token', type: 'Attack', cost: 0, target: 'AnyEnemy', keywords: ['Exhaust'], tags: ['Minion'], damage: 13 },
  'CARD.MINION_SACRIFICE': { name: 'Minion Sacrifice', color: 'Token', rarity: 'Token', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], tags: ['Minion'], block: 9 },
  'CARD.MINION_STRIKE': { name: 'Minion Strike', color: 'Token', rarity: 'Token', type: 'Attack', cost: 0, target: 'AnyEnemy', keywords: ['Exhaust'], tags: ['Strike', 'Minion'], damage: 6, cardsDraw: 1 },
  'CARD.MIRAGE': { name: 'Mirage', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self', keywords: ['Exhaust'], damage: 0 },
  'CARD.MISERY': { name: 'Misery', color: 'Necrobinder', rarity: 'Rare', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 7 },
  'CARD.MODDED': { name: 'Modded', color: 'Defect', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', cardsDraw: 1 },
  'CARD.MOLTEN_FIST': { name: 'Molten Fist', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', keywords: ['Exhaust'], damage: 10 },
  'CARD.MOMENTUM_STRIKE': { name: 'Momentum Strike', color: 'Defect', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 10 },
  'CARD.MONARCHS_GAZE': { name: 'Monarch\'s Gaze', color: 'Regent', rarity: 'Rare', type: 'Power', cost: 3, costUpgraded: 2, target: 'Self' },
  'CARD.MONOLOGUE': { name: 'Monologue', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self' },
  'CARD.MULTI_CAST': { name: 'Multi-Cast', color: 'Defect', rarity: 'Rare', type: 'Skill', cost: 0, isXCost: true, target: 'Self' },
  'CARD.MURDER': { name: 'Murder', color: 'Silent', rarity: 'Rare', type: 'Attack', cost: 3, costUpgraded: 2, target: 'AnyEnemy', damage: 1 },
  'CARD.NECRO_MASTERY': { name: 'Necro Mastery', color: 'Necrobinder', rarity: 'Rare', type: 'Power', cost: 2, target: 'Self' },
  'CARD.NEGATIVE_PULSE': { name: 'Negative Pulse', color: 'Necrobinder', rarity: 'Common', type: 'Skill', cost: 1, target: 'AllEnemies', block: 5, powersApplied: { "Doom": 7 } },
  'CARD.NEOWS_FURY': { name: 'Neow\'s Fury', color: 'Event', rarity: 'Ancient', type: 'Attack', cost: 1, target: 'AnyEnemy', keywords: ['Exhaust'], damage: 10, cardsDraw: 2 },
  'CARD.NEUROSURGE': { name: 'Neurosurge', color: 'Necrobinder', rarity: 'Rare', type: 'Power', cost: 0, target: 'Self', cardsDraw: 2, energyGain: 3, powersApplied: { "Neurosurge": 3 } },
  'CARD.NEUTRALIZE': { name: 'Neutralize', color: 'Silent', rarity: 'Basic', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 3, powersApplied: { "Weak": 1 } },
  'CARD.NEUTRON_AEGIS': { name: 'Neutron Aegis', color: 'Regent', rarity: 'Rare', type: 'Power', cost: 1, starCost: 5, target: 'Self', powersApplied: { "Plating": 8 } },
  'CARD.NIGHTMARE': { name: 'Nightmare', color: 'Silent', rarity: 'Rare', type: 'Skill', cost: 3, costUpgraded: 2, target: 'Self', keywords: ['Exhaust'] },
  'CARD.NO_ESCAPE': { name: 'No Escape', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AnyEnemy', damage: 10 },
  'CARD.NORMALITY': { name: 'Normality', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Unplayable'], damage: 3 },
  'CARD.NOSTALGIA': { name: 'Nostalgia', color: 'Colorless', rarity: 'Rare', type: 'Power', cost: 1, costUpgraded: 0, target: 'Self' },
  'CARD.NOT_YET': { name: 'Not Yet', color: 'Ironclad', rarity: 'Rare', type: 'Skill', cost: 2, target: 'Self', keywords: ['Exhaust'] },
  'CARD.NOXIOUS_FUMES': { name: 'Noxious Fumes', color: 'Silent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self' },
  'CARD.NULL': { name: 'Null', color: 'Defect', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 10, powersApplied: { "Weak": 2 } },
  'CARD.OBLIVION': { name: 'Oblivion', color: 'Necrobinder', rarity: 'Rare', type: 'Skill', cost: 0, target: 'AnyEnemy', powersApplied: { "Doom": 3 } },
  'CARD.OFFERING': { name: 'Offering', color: 'Ironclad', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], cardsDraw: 3, energyGain: 2, hpLoss: 6 },
  'CARD.OMNISLICE': { name: 'Omnislice', color: 'Colorless', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 8 },
  'CARD.ONE_TWO_PUNCH': { name: 'One-Two Punch', color: 'Ironclad', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self' },
  'CARD.ORBIT': { name: 'Orbit', color: 'Regent', rarity: 'Uncommon', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self', energyGain: 1 },
  'CARD.OUTBREAK': { name: 'Outbreak', color: 'Silent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Outbreak": 11 } },
  'CARD.OUTMANEUVER': { name: 'Outmaneuver', color: 'Event', rarity: 'Event', type: 'Skill', cost: 1, target: 'Self', energyGain: 2 },
  'CARD.OVERCLOCK': { name: 'Overclock', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', cardsDraw: 2, spawnsCards: ['BURN'] },
  'CARD.PACTS_END': { name: 'Pact\'s End', color: 'Ironclad', rarity: 'Rare', type: 'Attack', cost: 0, target: 'AllEnemies', damage: 17, cardsDraw: 3 },
  'CARD.PAGESTORM': { name: 'Pagestorm', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power', cost: 1, costUpgraded: 0, target: 'Self', cardsDraw: 1 },
  'CARD.PALE_BLUE_DOT': { name: 'Pale Blue Dot', color: 'Regent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', cardsDraw: 1 },
  'CARD.PANACHE': { name: 'Panache', color: 'Colorless', rarity: 'Uncommon', type: 'Power', cost: 0, target: 'Self' },
  'CARD.PANIC_BUTTON': { name: 'Panic Button', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], block: 30 },
  'CARD.PARRY': { name: 'Parry', color: 'Regent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Parry": 10 }, spawnsCards: ['SOVEREIGN_BLADE'] },
  'CARD.PARSE': { name: 'Parse', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', keywords: ['Ethereal'], cardsDraw: 3 },
  'CARD.PARTICLE_WALL': { name: 'Particle Wall', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 0, starCost: 2, target: 'Self', block: 9 },
  'CARD.PATTER': { name: 'Patter', color: 'Regent', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 9, powersApplied: { "Vigor": 2 } },
  'CARD.PECK': { name: 'Peck', color: 'Event', rarity: 'Event', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 2, hitCount: 3 },
  'CARD.PERFECTED_STRIKE': { name: 'Perfected Strike', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 2, target: 'AnyEnemy', tags: ['Strike'], damage: 6 },
  'CARD.PHANTOM_BLADES': { name: 'Phantom Blades', color: 'Silent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "PhantomBlades": 9 }, spawnsCards: ['SHIV'] },
  'CARD.PHOTON_CUT': { name: 'Photon Cut', color: 'Regent', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 10, cardsDraw: 1 },
  'CARD.PIERCING_WAIL': { name: 'Piercing Wail', color: 'Silent', rarity: 'Common', type: 'Skill', cost: 1, target: 'AllEnemies', keywords: ['Exhaust'] },
  'CARD.PILLAGE': { name: 'Pillage', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 6 },
  'CARD.PILLAR_OF_CREATION': { name: 'Pillar of Creation', color: 'Regent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', block: 3 },
  'CARD.PINPOINT': { name: 'Pinpoint', color: 'Silent', rarity: 'Uncommon', type: 'Attack', cost: 3, target: 'AnyEnemy', damage: 15 },
  'CARD.POISONED_STAB': { name: 'Poisoned Stab', color: 'Silent', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 6, powersApplied: { "Poison": 3 } },
  'CARD.POKE': { name: 'Poke', color: 'Necrobinder', rarity: 'Common', type: 'Attack', cost: 0, target: 'AnyEnemy', tags: ['OstyAttack'], damage: 6 },
  'CARD.POMMEL_STRIKE': { name: 'Pommel Strike', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 9, cardsDraw: 1 },
  'CARD.POOR_SLEEP': { name: 'Poor Sleep', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Retain', 'Unplayable'] },
  'CARD.POUNCE': { name: 'Pounce', color: 'Silent', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 12 },
  'CARD.PRECISE_CUT': { name: 'Precise Cut', color: 'Silent', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 13 },
  'CARD.PREDATOR': { name: 'Predator', color: 'Silent', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 15 },
  'CARD.PREP_TIME': { name: 'Prep Time', color: 'Colorless', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "PrepTime": 4 } },
  'CARD.PREPARED': { name: 'Prepared', color: 'Silent', rarity: 'Common', type: 'Skill', cost: 0, target: 'Self', cardsDraw: 1 },
  'CARD.PRIMAL_FORCE': { name: 'Primal Force', color: 'Ironclad', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', spawnsCards: ['GIANT_ROCK'] },
  'CARD.PRODUCTION': { name: 'Production', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], energyGain: 2 },
  'CARD.PROLONG': { name: 'Prolong', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'] },
  'CARD.PROPHESIZE': { name: 'Prophesize', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'Self', cardsDraw: 6 },
  'CARD.PROTECTOR': { name: 'Protector', color: 'Necrobinder', rarity: 'Ancient', type: 'Attack', cost: 1, costUpgraded: 0, target: 'AnyEnemy', tags: ['OstyAttack'], damage: 10 },
  'CARD.PROWESS': { name: 'Prowess', color: 'Colorless', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Strength": 1, "Dexterity": 1 } },
  'CARD.PULL_AGGRO': { name: 'Pull Aggro', color: 'Necrobinder', rarity: 'Common', type: 'Skill', cost: 2, target: 'Self', block: 7 },
  'CARD.PULL_FROM_BELOW': { name: 'Pull from Below', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 5 },
  'CARD.PURITY': { name: 'Purity', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust', 'Retain'], cardsDraw: 3 },
  'CARD.PUTREFY': { name: 'Putrefy', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AnyEnemy', keywords: ['Exhaust'] },
  'CARD.PYRE': { name: 'Pyre', color: 'Ironclad', rarity: 'Rare', type: 'Power', cost: 2, target: 'Self', energyGain: 1 },
  'CARD.QUADCAST': { name: 'Quadcast', color: 'Defect', rarity: 'Ancient', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self' },
  'CARD.QUASAR': { name: 'Quasar', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 0, starCost: 2, target: 'Self' },
  'CARD.RADIATE': { name: 'Radiate', color: 'Regent', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AllEnemies', damage: 3 },
  'CARD.RAGE': { name: 'Rage', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self' },
  'CARD.RAINBOW': { name: 'Rainbow', color: 'Defect', rarity: 'Rare', type: 'Skill', cost: 2, target: 'Self', keywords: ['Exhaust'] },
  'CARD.RALLY': { name: 'Rally', color: 'Colorless', rarity: 'Rare', type: 'Skill', cost: 2, target: 'AllAllies', block: 12 },
  'CARD.RAMPAGE': { name: 'Rampage', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 9 },
  'CARD.RATTLE': { name: 'Rattle', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['OstyAttack'], damage: 7 },
  'CARD.REANIMATE': { name: 'Reanimate', color: 'Necrobinder', rarity: 'Rare', type: 'Skill', cost: 3, target: 'Self', keywords: ['Exhaust'] },
  'CARD.REAP': { name: 'Reap', color: 'Necrobinder', rarity: 'Common', type: 'Attack', cost: 3, target: 'AnyEnemy', keywords: ['Retain'], damage: 27 },
  'CARD.REAPER_FORM': { name: 'Reaper Form', color: 'Necrobinder', rarity: 'Rare', type: 'Power', cost: 3, target: 'Self' },
  'CARD.REAVE': { name: 'Reave', color: 'Necrobinder', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 9, cardsDraw: 1, spawnsCards: ['SOUL'] },
  'CARD.REBOOT': { name: 'Reboot', color: 'Defect', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], cardsDraw: 4 },
  'CARD.REBOUND': { name: 'Rebound', color: 'Event', rarity: 'Event', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 9 },
  'CARD.REFINE_BLADE': { name: 'Refine Blade', color: 'Regent', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', energyGain: 1 },
  'CARD.REFLECT': { name: 'Reflect', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 1, starCost: 3, target: 'Self', block: 16 },
  'CARD.REFLEX': { name: 'Reflex', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 3, target: 'Self', keywords: ['Sly'], cardsDraw: 2 },
  'CARD.REFRACT': { name: 'Refract', color: 'Defect', rarity: 'Uncommon', type: 'Attack', cost: 3, target: 'AnyEnemy', damage: 9, hitCount: 2 },
  'CARD.REGRET': { name: 'Regret', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Unplayable'] },
  'CARD.RELAX': { name: 'Relax', color: 'Event', rarity: 'Ancient', type: 'Skill', cost: 3, target: 'Self', keywords: ['Exhaust'], block: 15, cardsDraw: 2, energyGain: 2 },
  'CARD.REND': { name: 'Rend', color: 'Colorless', rarity: 'Rare', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 15 },
  'CARD.RESONANCE': { name: 'Resonance', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 1, starCost: 3, target: 'AllEnemies', powersApplied: { "Strength": 1 } },
  'CARD.RESTLESSNESS': { name: 'Restlessness', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', keywords: ['Retain'], cardsDraw: 2, energyGain: 2 },
  'CARD.RICOCHET': { name: 'Ricochet', color: 'Silent', rarity: 'Common', type: 'Attack', cost: 2, target: 'RandomEnemy', keywords: ['Sly'], damage: 3, hitCount: 4 },
  'CARD.RIGHT_HAND_HAND': { name: 'Right Hand Hand', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AnyEnemy', tags: ['OstyAttack'], damage: 4, energyGain: 2 },
  'CARD.RIP_AND_TEAR': { name: 'Rip and Tear', color: 'Event', rarity: 'Event', type: 'Attack', cost: 1, target: 'RandomEnemy', damage: 7, hitCount: 2 },
  'CARD.ROCKET_PUNCH': { name: 'Rocket Punch', color: 'Defect', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 13, cardsDraw: 1 },
  'CARD.ROLLING_BOULDER': { name: 'Rolling Boulder', color: 'Colorless', rarity: 'Rare', type: 'Power', cost: 3, target: 'Self', powersApplied: { "RollingBoulder": 5 } },
  'CARD.ROYAL_GAMBLE': { name: 'Royal Gamble', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 0, starCost: 5, target: 'Self', keywords: ['Exhaust'] },
  'CARD.ROYALTIES': { name: 'Royalties', color: 'Regent', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self' },
  'CARD.RUPTURE': { name: 'Rupture', color: 'Ironclad', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Strength": 1 } },
  'CARD.SACRIFICE': { name: 'Sacrifice', color: 'Necrobinder', rarity: 'Rare', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self', keywords: ['Retain'] },
  'CARD.SALVO': { name: 'Salvo', color: 'Colorless', rarity: 'Rare', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 12 },
  'CARD.SCAVENGE': { name: 'Scavenge', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', energyGain: 2 },
  'CARD.SCOURGE': { name: 'Scourge', color: 'Necrobinder', rarity: 'Common', type: 'Skill', cost: 1, target: 'AnyEnemy', cardsDraw: 1, powersApplied: { "Doom": 13 } },
  'CARD.SCRAPE': { name: 'Scrape', color: 'Defect', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 7, cardsDraw: 4 },
  'CARD.SCRAWL': { name: 'Scrawl', color: 'Colorless', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust'] },
  'CARD.SCULPTING_STRIKE': { name: 'Sculpting Strike', color: 'Necrobinder', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 9 },
  'CARD.SEANCE': { name: 'Seance', color: 'Necrobinder', rarity: 'Rare', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self', keywords: ['Ethereal'], cardsDraw: 1, spawnsCards: ['SOUL'] },
  'CARD.SECOND_WIND': { name: 'Second Wind', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', block: 5 },
  'CARD.SECRET_TECHNIQUE': { name: 'Secret Technique', color: 'Colorless', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'] },
  'CARD.SECRET_WEAPON': { name: 'Secret Weapon', color: 'Colorless', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'] },
  'CARD.SEEKER_STRIKE': { name: 'Seeker Strike', color: 'Colorless', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 9, cardsDraw: 3 },
  'CARD.SEEKING_EDGE': { name: 'Seeking Edge', color: 'Regent', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self' },
  'CARD.SENTRY_MODE': { name: 'Sentry Mode', color: 'Necrobinder', rarity: 'Rare', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self', powersApplied: { "SentryMode": 1 }, spawnsCards: ['SWEEPING_GAZE'] },
  'CARD.SERPENT_FORM': { name: 'Serpent Form', color: 'Silent', rarity: 'Rare', type: 'Power', cost: 3, target: 'Self', powersApplied: { "SerpentForm": 4 } },
  'CARD.SETUP_STRIKE': { name: 'Setup Strike', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 7, powersApplied: { "Strength": 2 } },
  'CARD.SEVEN_STARS': { name: 'Seven Stars', color: 'Regent', rarity: 'Rare', type: 'Attack', cost: 2, costUpgraded: 1, starCost: 7, target: 'AllEnemies', damage: 7, hitCount: 7 },
  'CARD.SEVERANCE': { name: 'Severance', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 13, spawnsCards: ['SOUL'] },
  'CARD.SHADOW_SHIELD': { name: 'Shadow Shield', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'Self', block: 11 },
  'CARD.SHADOW_STEP': { name: 'Shadow Step', color: 'Silent', rarity: 'Rare', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self', cardsDraw: 3 },
  'CARD.SHADOWMELD': { name: 'Shadowmeld', color: 'Silent', rarity: 'Rare', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self' },
  'CARD.SHAME': { name: 'Shame', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Unplayable'] },
  'CARD.SHARED_FATE': { name: 'Shared Fate', color: 'Necrobinder', rarity: 'Rare', type: 'Skill', cost: 0, target: 'AnyEnemy', keywords: ['Exhaust'] },
  'CARD.SHATTER': { name: 'Shatter', color: 'Defect', rarity: 'Rare', type: 'Attack', cost: 1, target: 'AllEnemies', damage: 11 },
  'CARD.SHINING_STRIKE': { name: 'Shining Strike', color: 'Regent', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 8 },
  'CARD.SHIV': { name: 'Shiv', color: 'Token', rarity: 'Token', type: 'Attack', cost: 0, target: 'AnyEnemy', keywords: ['Exhaust'], tags: ['Shiv'], damage: 4 },
  'CARD.SHOCKWAVE': { name: 'Shockwave', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'AllEnemies', keywords: ['Exhaust'] },
  'CARD.SHROUD': { name: 'Shroud', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', block: 2 },
  'CARD.SHRUG_IT_OFF': { name: 'Shrug It Off', color: 'Ironclad', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 8, cardsDraw: 1 },
  'CARD.SIC_EM': { name: 'Sic \'Em', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['OstyAttack'], damage: 5, powersApplied: { "SicEm": 2 } },
  'CARD.SIGNAL_BOOST': { name: 'Signal Boost', color: 'Defect', rarity: 'Rare', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self', keywords: ['Exhaust'], powersApplied: { "SignalBoost": 1 } },
  'CARD.SKEWER': { name: 'Skewer', color: 'Silent', rarity: 'Uncommon', type: 'Attack', cost: 0, isXCost: true, target: 'AnyEnemy', damage: 8 },
  'CARD.SKIM': { name: 'Skim', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 3 },
  'CARD.SLEIGHT_OF_FLESH': { name: 'Sleight of Flesh', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power', cost: 2, target: 'Self', powersApplied: { "SleightOfFlesh": 9 } },
  'CARD.SLICE': { name: 'Slice', color: 'Silent', rarity: 'Common', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 6 },
  'CARD.SLIMED': { name: 'Slimed', color: 'Status', rarity: 'Status', type: 'Status', cost: 1, target: 'None', keywords: ['Exhaust'], cardsDraw: 1 },
  'CARD.SLOTH': { name: 'Sloth', color: 'Token', rarity: 'Status', type: 'Status', cost: -1, target: 'None', powersApplied: { "Sloth": 3 } },
  'CARD.SMOKESTACK': { name: 'Smokestack', color: 'Defect', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Smokestack": 5 } },
  'CARD.SNAKEBITE': { name: 'Snakebite', color: 'Silent', rarity: 'Common', type: 'Skill', cost: 2, target: 'AnyEnemy', keywords: ['Retain'], powersApplied: { "Poison": 7 } },
  'CARD.SNAP': { name: 'Snap', color: 'Necrobinder', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['OstyAttack'], damage: 7 },
  'CARD.SNEAKY': { name: 'Sneaky', color: 'Silent', rarity: 'Rare', type: 'Power', cost: 2, target: 'Self', keywords: ['Sly'], powersApplied: { "Sneaky": 1 } },
  'CARD.SOLAR_STRIKE': { name: 'Solar Strike', color: 'Regent', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 9 },
  'CARD.SOOT': { name: 'Soot', color: 'Status', rarity: 'Status', type: 'Status', cost: -1, target: 'None', keywords: ['Unplayable'] },
  'CARD.SOUL': { name: 'Soul', color: 'Token', rarity: 'Token', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], cardsDraw: 2 },
  'CARD.SOUL_STORM': { name: 'Soul Storm', color: 'Necrobinder', rarity: 'Rare', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 9, spawnsCards: ['SOUL'] },
  'CARD.SOVEREIGN_BLADE': { name: 'Sovereign Blade', color: 'Token', rarity: 'Token', type: 'Attack', cost: 2, costUpgraded: 1, target: 'AnyEnemy', keywords: ['Retain'], damage: 10, hitCount: 1 },
  'CARD.SOW': { name: 'Sow', color: 'Necrobinder', rarity: 'Common', type: 'Attack', cost: 1, target: 'AllEnemies', keywords: ['Retain'], damage: 8 },
  'CARD.SPECTRUM_SHIFT': { name: 'Spectrum Shift', color: 'Regent', rarity: 'Uncommon', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self', cardsDraw: 1 },
  'CARD.SPEEDSTER': { name: 'Speedster', color: 'Silent', rarity: 'Uncommon', type: 'Power', cost: 2, target: 'Self', powersApplied: { "Speedster": 2 } },
  'CARD.SPINNER': { name: 'Spinner', color: 'Defect', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Spinner": 1 } },
  'CARD.SPIRIT_OF_ASH': { name: 'Spirit of Ash', color: 'Necrobinder', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self' },
  'CARD.SPITE': { name: 'Spite', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 5, hitCount: 2 },
  'CARD.SPLASH': { name: 'Splash', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self' },
  'CARD.SPOILS_MAP': { name: 'Spoils Map', color: 'Quest', rarity: 'Quest', type: 'Quest', cost: -1, target: 'Self', keywords: ['Unplayable'] },
  'CARD.SPOILS_OF_BATTLE': { name: 'Spoils of Battle', color: 'Regent', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', cardsDraw: 2 },
  'CARD.SPORE_MIND': { name: 'Spore Mind', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: 1, target: 'None', keywords: ['Exhaust'] },
  'CARD.SPUR': { name: 'Spur', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', keywords: ['Retain'] },
  'CARD.SQUASH': { name: 'Squash', color: 'Event', rarity: 'Event', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 10, powersApplied: { "Vulnerable": 2 } },
  'CARD.SQUEEZE': { name: 'Squeeze', color: 'Necrobinder', rarity: 'Rare', type: 'Attack', cost: 3, target: 'AnyEnemy', tags: ['OstyAttack'], damage: 25 },
  'CARD.STACK': { name: 'Stack', color: 'Event', rarity: 'Event', type: 'Skill', cost: 1, target: 'Self', damage: 0 },
  'CARD.STAMPEDE': { name: 'Stampede', color: 'Ironclad', rarity: 'Uncommon', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self' },
  'CARD.STARDUST': { name: 'Stardust', color: 'Regent', rarity: 'Uncommon', type: 'Attack', cost: 0, isXStarCost: true, target: 'RandomEnemy', damage: 5 },
  'CARD.STOKE': { name: 'Stoke', color: 'Ironclad', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self' },
  'CARD.STOMP': { name: 'Stomp', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 3, target: 'AllEnemies', damage: 12 },
  'CARD.STONE_ARMOR': { name: 'Stone Armor', color: 'Ironclad', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Plating": 4 } },
  'CARD.STORM': { name: 'Storm', color: 'Defect', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Storm": 1 } },
  'CARD.STORM_OF_STEEL': { name: 'Storm of Steel', color: 'Silent', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self', spawnsCards: ['SHIV'] },
  'CARD.STRANGLE': { name: 'Strangle', color: 'Silent', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 8, powersApplied: { "Strangle": 2 } },
  'CARD.STRATAGEM': { name: 'Stratagem', color: 'Colorless', rarity: 'Uncommon', type: 'Power', cost: 1, costUpgraded: 0, target: 'Self' },
  'CARD.STRIKE_IRONCLAD': { name: 'Strike', color: 'Ironclad', rarity: 'Basic', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 6 },
  'CARD.STRIKE_SILENT': { name: 'Strike', color: 'Silent', rarity: 'Basic', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 6 },
  'CARD.STRIKE_REGENT': { name: 'Strike', color: 'Regent', rarity: 'Basic', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 6 },
  'CARD.STRIKE_NECROBINDER': { name: 'Strike', color: 'Necrobinder', rarity: 'Basic', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 6 },
  'CARD.STRIKE_DEFECT': { name: 'Strike', color: 'Defect', rarity: 'Basic', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 6 },
  'CARD.SUBROUTINE': { name: 'Subroutine', color: 'Defect', rarity: 'Uncommon', type: 'Power', cost: 1, costUpgraded: 0, target: 'Self' },
  'CARD.SUCKER_PUNCH': { name: 'Sucker Punch', color: 'Silent', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 8, powersApplied: { "Weak": 1 } },
  'CARD.SUMMON_FORTH': { name: 'Summon Forth', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', spawnsCards: ['SOVEREIGN_BLADE'] },
  'CARD.SUNDER': { name: 'Sunder', color: 'Defect', rarity: 'Uncommon', type: 'Attack', cost: 3, target: 'AnyEnemy', damage: 24, energyGain: 3 },
  'CARD.SUPERCRITICAL': { name: 'Supercritical', color: 'Defect', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], energyGain: 4 },
  'CARD.SUPERMASSIVE': { name: 'Supermassive', color: 'Regent', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 5 },
  'CARD.SUPPRESS': { name: 'Suppress', color: 'Silent', rarity: 'Ancient', type: 'Attack', cost: 0, target: 'AnyEnemy', keywords: ['Innate'], damage: 11, powersApplied: { "Weak": 3 } },
  'CARD.SURVIVOR': { name: 'Survivor', color: 'Silent', rarity: 'Basic', type: 'Skill', cost: 1, target: 'Self', block: 8 },
  'CARD.SWEEPING_BEAM': { name: 'Sweeping Beam', color: 'Defect', rarity: 'Common', type: 'Attack', cost: 1, target: 'AllEnemies', damage: 6, cardsDraw: 1 },
  'CARD.SWEEPING_GAZE': { name: 'Sweeping Gaze', color: 'Token', rarity: 'Token', type: 'Attack', cost: 0, target: 'RandomEnemy', keywords: ['Exhaust', 'Ethereal'], tags: ['OstyAttack'], damage: 10 },
  'CARD.SWORD_BOOMERANG': { name: 'Sword Boomerang', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 1, target: 'RandomEnemy', damage: 3, hitCount: 3 },
  'CARD.SWORD_SAGE': { name: 'Sword Sage', color: 'Regent', rarity: 'Rare', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self', powersApplied: { "SwordSage": 1 }, spawnsCards: ['SOVEREIGN_BLADE'] },
  'CARD.SYNCHRONIZE': { name: 'Synchronize', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust'], damage: 0 },
  'CARD.SYNTHESIS': { name: 'Synthesis', color: 'Defect', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 12 },
  'CARD.TURBO': { name: 'TURBO', color: 'Defect', rarity: 'Common', type: 'Skill', cost: 0, target: 'Self', energyGain: 2, spawnsCards: ['VOID'] },
  'CARD.TACTICIAN': { name: 'Tactician', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 3, target: 'Self', keywords: ['Sly'], energyGain: 1 },
  'CARD.TAG_TEAM': { name: 'Tag Team', color: 'Colorless', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 11 },
  'CARD.TANK': { name: 'Tank', color: 'Ironclad', rarity: 'Rare', type: 'Power', cost: 1, costUpgraded: 0, target: 'Self' },
  'CARD.TAUNT': { name: 'Taunt', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'AnyEnemy', block: 7, powersApplied: { "Vulnerable": 1 } },
  'CARD.TEAR_ASUNDER': { name: 'Tear Asunder', color: 'Ironclad', rarity: 'Rare', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 5, hitCount: 1 },
  'CARD.TEMPEST': { name: 'Tempest', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 0, isXCost: true, target: 'Self' },
  'CARD.TERRAFORMING': { name: 'Terraforming', color: 'Regent', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', powersApplied: { "Vigor": 6 } },
  'CARD.TESLA_COIL': { name: 'Tesla Coil', color: 'Defect', rarity: 'Uncommon', type: 'Attack', cost: 0, target: 'AnyEnemy', damage: 3 },
  'CARD.THE_BOMB': { name: 'The Bomb', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'Self' },
  'CARD.THE_GAMBIT': { name: 'The Gambit', color: 'Colorless', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', block: 50 },
  'CARD.THE_HUNT': { name: 'The Hunt', color: 'Silent', rarity: 'Rare', type: 'Attack', cost: 1, target: 'AnyEnemy', keywords: ['Exhaust'], damage: 10 },
  'CARD.THE_SCYTHE': { name: 'The Scythe', color: 'Necrobinder', rarity: 'Rare', type: 'Attack', cost: 2, target: 'AnyEnemy', keywords: ['Exhaust'], damage: 13 },
  'CARD.THE_SEALED_THRONE': { name: 'The Sealed Throne', color: 'Regent', rarity: 'Ancient', type: 'Power', cost: 1, starCost: 3, target: 'Self' },
  'CARD.THE_SMITH': { name: 'The Smith', color: 'Regent', rarity: 'Rare', type: 'Skill', cost: 1, starCost: 4, target: 'Self' },
  'CARD.THINKING_AHEAD': { name: 'Thinking Ahead', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], cardsDraw: 2 },
  'CARD.THRASH': { name: 'Thrash', color: 'Ironclad', rarity: 'Rare', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 4, hitCount: 2 },
  'CARD.THRUMMING_HATCHET': { name: 'Thrumming Hatchet', color: 'Colorless', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 11 },
  'CARD.THUNDER': { name: 'Thunder', color: 'Defect', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', powersApplied: { "Thunder": 6 } },
  'CARD.THUNDERCLAP': { name: 'Thunderclap', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 1, target: 'AllEnemies', damage: 4, powersApplied: { "Vulnerable": 1 } },
  'CARD.TIMES_UP': { name: 'Time\'s Up', color: 'Necrobinder', rarity: 'Rare', type: 'Attack', cost: 2, target: 'AnyEnemy', keywords: ['Exhaust'], damage: 0 },
  'CARD.TOOLS_OF_THE_TRADE': { name: 'Tools of the Trade', color: 'Silent', rarity: 'Rare', type: 'Power', cost: 1, costUpgraded: 0, target: 'Self' },
  'CARD.TORIC_TOUGHNESS': { name: 'Toric Toughness', color: 'Event', rarity: 'Event', type: 'Skill', cost: 2, target: 'Self', block: 5 },
  'CARD.TOXIC': { name: 'Toxic', color: 'Status', rarity: 'Status', type: 'Status', cost: 1, target: 'None', keywords: ['Exhaust'], damage: 5 },
  'CARD.TRACKING': { name: 'Tracking', color: 'Silent', rarity: 'Rare', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self' },
  'CARD.TRANSFIGURE': { name: 'Transfigure', color: 'Necrobinder', rarity: 'Rare', type: 'Skill', cost: 1, target: 'Self', keywords: ['Exhaust'], energyGain: 1 },
  'CARD.TRASH_TO_TREASURE': { name: 'Trash to Treasure', color: 'Defect', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self' },
  'CARD.TREMBLE': { name: 'Tremble', color: 'Ironclad', rarity: 'Common', type: 'Skill', cost: 1, target: 'AnyEnemy', keywords: ['Exhaust'], powersApplied: { "Vulnerable": 3 } },
  'CARD.TRUE_GRIT': { name: 'True Grit', color: 'Ironclad', rarity: 'Common', type: 'Skill', cost: 1, target: 'Self', block: 7 },
  'CARD.TWIN_STRIKE': { name: 'Twin Strike', color: 'Ironclad', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 5, hitCount: 2 },
  'CARD.TYRANNY': { name: 'Tyranny', color: 'Regent', rarity: 'Rare', type: 'Power', cost: 1, target: 'Self', keywords: ['Exhaust'] },
  'CARD.ULTIMATE_DEFEND': { name: 'Ultimate Defend', color: 'Colorless', rarity: 'Uncommon', type: 'Skill', cost: 1, target: 'Self', tags: ['Defend'], block: 11 },
  'CARD.ULTIMATE_STRIKE': { name: 'Ultimate Strike', color: 'Colorless', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['Strike'], damage: 14 },
  'CARD.UNDEATH': { name: 'Undeath', color: 'Necrobinder', rarity: 'Rare', type: 'Skill', cost: 0, target: 'Self', block: 7 },
  'CARD.UNLEASH': { name: 'Unleash', color: 'Necrobinder', rarity: 'Basic', type: 'Attack', cost: 1, target: 'AnyEnemy', tags: ['OstyAttack'], damage: 6 },
  'CARD.UNMOVABLE': { name: 'Unmovable', color: 'Ironclad', rarity: 'Rare', type: 'Power', cost: 2, costUpgraded: 1, target: 'Self' },
  'CARD.UNRELENTING': { name: 'Unrelenting', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 12 },
  'CARD.UNTOUCHABLE': { name: 'Untouchable', color: 'Silent', rarity: 'Common', type: 'Skill', cost: 2, target: 'Self', keywords: ['Sly'], block: 6 },
  'CARD.UP_MY_SLEEVE': { name: 'Up My Sleeve', color: 'Silent', rarity: 'Uncommon', type: 'Skill', cost: 2, target: 'Self', cardsDraw: 3, spawnsCards: ['SHIV'] },
  'CARD.UPPERCUT': { name: 'Uppercut', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 13 },
  'CARD.UPROAR': { name: 'Uproar', color: 'Defect', rarity: 'Common', type: 'Attack', cost: 2, target: 'AnyEnemy', damage: 5, hitCount: 2 },
  'CARD.VEILPIERCER': { name: 'Veilpiercer', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 10 },
  'CARD.VENERATE': { name: 'Venerate', color: 'Regent', rarity: 'Basic', type: 'Skill', cost: 1, target: 'Self' },
  'CARD.VICIOUS': { name: 'Vicious', color: 'Ironclad', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self', cardsDraw: 1 },
  'CARD.VOID': { name: 'Void', color: 'Status', rarity: 'Status', type: 'Status', cost: -1, target: 'None', keywords: ['Ethereal', 'Unplayable'], energyGain: 1 },
  'CARD.VOID_FORM': { name: 'Void Form', color: 'Regent', rarity: 'Rare', type: 'Power', cost: 3, target: 'Self', keywords: ['Ethereal'], powersApplied: { "VoidForm": 2 } },
  'CARD.VOLLEY': { name: 'Volley', color: 'Colorless', rarity: 'Uncommon', type: 'Attack', cost: 0, isXCost: true, target: 'RandomEnemy', damage: 10 },
  'CARD.VOLTAIC': { name: 'Voltaic', color: 'Defect', rarity: 'Rare', type: 'Skill', cost: 3, target: 'Self', keywords: ['Exhaust'], damage: 0 },
  'CARD.WASTE_AWAY': { name: 'Waste Away', color: 'Token', rarity: 'Status', type: 'Status', cost: -1, target: 'None', powersApplied: { "WasteAway": 1 } },
  'CARD.WELL_LAID_PLANS': { name: 'Well-Laid Plans', color: 'Silent', rarity: 'Uncommon', type: 'Power', cost: 1, target: 'Self' },
  'CARD.WHIRLWIND': { name: 'Whirlwind', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack', cost: 0, isXCost: true, target: 'AllEnemies', damage: 5 },
  'CARD.WHISTLE': { name: 'Whistle', color: 'Event', rarity: 'Ancient', type: 'Attack', cost: 3, target: 'AnyEnemy', keywords: ['Exhaust'], damage: 33 },
  'CARD.WHITE_NOISE': { name: 'White Noise', color: 'Defect', rarity: 'Uncommon', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self', keywords: ['Exhaust'] },
  'CARD.WISH': { name: 'Wish', color: 'Event', rarity: 'Ancient', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'] },
  'CARD.WISP': { name: 'Wisp', color: 'Necrobinder', rarity: 'Common', type: 'Skill', cost: 0, target: 'Self', keywords: ['Exhaust'], energyGain: 1 },
  'CARD.WOUND': { name: 'Wound', color: 'Status', rarity: 'Status', type: 'Status', cost: -1, target: 'None', keywords: ['Unplayable'] },
  'CARD.WRAITH_FORM': { name: 'Wraith Form', color: 'Silent', rarity: 'Ancient', type: 'Power', cost: 3, target: 'Self', powersApplied: { "Intangible": 2, "WraithForm": 1 } },
  'CARD.WRITHE': { name: 'Writhe', color: 'Curse', rarity: 'Curse', type: 'Curse', cost: -1, target: 'None', keywords: ['Innate', 'Unplayable'] },
  'CARD.WROUGHT_IN_WAR': { name: 'Wrought in War', color: 'Regent', rarity: 'Common', type: 'Attack', cost: 1, target: 'AnyEnemy', damage: 7 },
  'CARD.ZAP': { name: 'Zap', color: 'Defect', rarity: 'Basic', type: 'Skill', cost: 1, costUpgraded: 0, target: 'Self' },
};

function stripCardId(cardId: string): { baseId: string; upgraded: boolean } {
  // Strip enchantment suffix like " [ENCHANTMENT.SWIFT]"
  const bracketIdx = cardId.indexOf(' [');
  const withoutEnchantment = bracketIdx !== -1 ? cardId.slice(0, bracketIdx) : cardId;
  const upgraded = withoutEnchantment.endsWith('+');
  const baseId = upgraded ? withoutEnchantment.slice(0, -1) : withoutEnchantment;
  return { baseId, upgraded };
}

export function getCardMeta(cardId: string): CardMeta | undefined {
  return CARD_META[stripCardId(cardId).baseId];
}

// Returns the energy cost of a card, accounting for upgrade status (trailing '+').
// Returns -1 for unplayable curses/statuses; check meta.isXCost to disambiguate
// the rare X-cost card that also reports -1 (Cascade).
export function getCardCost(cardId: string): number | undefined {
  const { baseId, upgraded } = stripCardId(cardId);
  const meta = CARD_META[baseId];
  if (!meta) return undefined;
  return upgraded && meta.costUpgraded !== undefined ? meta.costUpgraded : meta.cost;
}
