// Auto-generated from https://github.com/ptrlrd/spire-codex (v0.103.0)
// 577 cards — regenerate with: node scripts/generate-meta.mjs

export type CardColor = 'Colorless' | 'Curse' | 'Defect' | 'Event' | 'Ironclad' | 'Necrobinder' | 'Quest' | 'Regent' | 'Silent' | 'Status' | 'Token' | 'Unknown';
export type CardRarity = 'Ancient' | 'Basic' | 'Common' | 'Curse' | 'Event' | 'Quest' | 'Rare' | 'Status' | 'Token' | 'Uncommon';
export type CardType = 'Attack' | 'Curse' | 'Power' | 'Quest' | 'Skill' | 'Status';

export interface CardMeta {
  name: string;
  color: CardColor;
  rarity: CardRarity;
  type: CardType;
}

const CARD_META: Record<string, CardMeta> = {
  'CARD.ABRASIVE': { name: 'Abrasive', color: 'Silent', rarity: 'Rare', type: 'Power' },
  'CARD.ACCELERANT': { name: 'Accelerant', color: 'Silent', rarity: 'Rare', type: 'Power' },
  'CARD.ACCURACY': { name: 'Accuracy', color: 'Silent', rarity: 'Uncommon', type: 'Power' },
  'CARD.ACROBATICS': { name: 'Acrobatics', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.ADAPTIVE_STRIKE': { name: 'Adaptive Strike', color: 'Defect', rarity: 'Rare', type: 'Attack' },
  'CARD.ADRENALINE': { name: 'Adrenaline', color: 'Silent', rarity: 'Rare', type: 'Skill' },
  'CARD.AFTERIMAGE': { name: 'Afterimage', color: 'Silent', rarity: 'Rare', type: 'Power' },
  'CARD.AFTERLIFE': { name: 'Afterlife', color: 'Necrobinder', rarity: 'Common', type: 'Skill' },
  'CARD.AGGRESSION': { name: 'Aggression', color: 'Ironclad', rarity: 'Rare', type: 'Power' },
  'CARD.ALCHEMIZE': { name: 'Alchemize', color: 'Colorless', rarity: 'Rare', type: 'Skill' },
  'CARD.ALIGNMENT': { name: 'Alignment', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.ALL_FOR_ONE': { name: 'All for One', color: 'Defect', rarity: 'Rare', type: 'Attack' },
  'CARD.ANGER': { name: 'Anger', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.ANOINTED': { name: 'Anointed', color: 'Colorless', rarity: 'Rare', type: 'Skill' },
  'CARD.ANTICIPATE': { name: 'Anticipate', color: 'Silent', rarity: 'Common', type: 'Skill' },
  'CARD.APOTHEOSIS': { name: 'Apotheosis', color: 'Event', rarity: 'Ancient', type: 'Skill' },
  'CARD.APPARITION': { name: 'Apparition', color: 'Event', rarity: 'Ancient', type: 'Skill' },
  'CARD.ARMAMENTS': { name: 'Armaments', color: 'Ironclad', rarity: 'Common', type: 'Skill' },
  'CARD.ARSENAL': { name: 'Arsenal', color: 'Regent', rarity: 'Rare', type: 'Power' },
  'CARD.ASCENDERS_BANE': { name: 'Ascender\'s Bane', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.ASHEN_STRIKE': { name: 'Ashen Strike', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.ASSASSINATE': { name: 'Assassinate', color: 'Silent', rarity: 'Rare', type: 'Attack' },
  'CARD.ASTRAL_PULSE': { name: 'Astral Pulse', color: 'Regent', rarity: 'Common', type: 'Attack' },
  'CARD.AUTOMATION': { name: 'Automation', color: 'Colorless', rarity: 'Uncommon', type: 'Power' },
  'CARD.BEGONE': { name: 'BEGONE!', color: 'Regent', rarity: 'Common', type: 'Skill' },
  'CARD.BACKFLIP': { name: 'Backflip', color: 'Silent', rarity: 'Common', type: 'Skill' },
  'CARD.BACKSTAB': { name: 'Backstab', color: 'Silent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.BAD_LUCK': { name: 'Bad Luck', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.BALL_LIGHTNING': { name: 'Ball Lightning', color: 'Defect', rarity: 'Common', type: 'Attack' },
  'CARD.BANSHEES_CRY': { name: 'Banshee\'s Cry', color: 'Necrobinder', rarity: 'Rare', type: 'Attack' },
  'CARD.BARRAGE': { name: 'Barrage', color: 'Defect', rarity: 'Common', type: 'Attack' },
  'CARD.BARRICADE': { name: 'Barricade', color: 'Ironclad', rarity: 'Rare', type: 'Power' },
  'CARD.BASH': { name: 'Bash', color: 'Ironclad', rarity: 'Basic', type: 'Attack' },
  'CARD.BATTLE_TRANCE': { name: 'Battle Trance', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.BEACON_OF_HOPE': { name: 'Beacon of Hope', color: 'Colorless', rarity: 'Rare', type: 'Power' },
  'CARD.BEAM_CELL': { name: 'Beam Cell', color: 'Defect', rarity: 'Common', type: 'Attack' },
  'CARD.BEAT_DOWN': { name: 'Beat Down', color: 'Colorless', rarity: 'Rare', type: 'Skill' },
  'CARD.BEAT_INTO_SHAPE': { name: 'Beat into Shape', color: 'Regent', rarity: 'Rare', type: 'Attack' },
  'CARD.BECKON': { name: 'Beckon', color: 'Status', rarity: 'Status', type: 'Status' },
  'CARD.BELIEVE_IN_YOU': { name: 'Believe in You', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.BIASED_COGNITION': { name: 'Biased Cognition', color: 'Defect', rarity: 'Ancient', type: 'Power' },
  'CARD.BIG_BANG': { name: 'Big Bang', color: 'Regent', rarity: 'Rare', type: 'Skill' },
  'CARD.BLACK_HOLE': { name: 'Black Hole', color: 'Regent', rarity: 'Uncommon', type: 'Power' },
  'CARD.BLADE_DANCE': { name: 'Blade Dance', color: 'Silent', rarity: 'Common', type: 'Skill' },
  'CARD.BLADE_OF_INK': { name: 'Blade of Ink', color: 'Silent', rarity: 'Rare', type: 'Skill' },
  'CARD.BLIGHT_STRIKE': { name: 'Blight Strike', color: 'Necrobinder', rarity: 'Common', type: 'Attack' },
  'CARD.BLOOD_WALL': { name: 'Blood Wall', color: 'Ironclad', rarity: 'Common', type: 'Skill' },
  'CARD.BLOODLETTING': { name: 'Bloodletting', color: 'Ironclad', rarity: 'Common', type: 'Skill' },
  'CARD.BLUDGEON': { name: 'Bludgeon', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.BLUR': { name: 'Blur', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.BODY_SLAM': { name: 'Body Slam', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.BODYGUARD': { name: 'Bodyguard', color: 'Necrobinder', rarity: 'Basic', type: 'Skill' },
  'CARD.BOLAS': { name: 'Bolas', color: 'Colorless', rarity: 'Rare', type: 'Attack' },
  'CARD.BOMBARDMENT': { name: 'Bombardment', color: 'Regent', rarity: 'Rare', type: 'Attack' },
  'CARD.BONE_SHARDS': { name: 'Bone Shards', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack' },
  'CARD.BOOST_AWAY': { name: 'Boost Away', color: 'Defect', rarity: 'Common', type: 'Skill' },
  'CARD.BOOT_SEQUENCE': { name: 'Boot Sequence', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.BORROWED_TIME': { name: 'Borrowed Time', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.BOUNCING_FLASK': { name: 'Bouncing Flask', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.BRAND': { name: 'Brand', color: 'Ironclad', rarity: 'Rare', type: 'Skill' },
  'CARD.BREAK': { name: 'Break', color: 'Ironclad', rarity: 'Ancient', type: 'Attack' },
  'CARD.BREAKTHROUGH': { name: 'Breakthrough', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.BRIGHTEST_FLAME': { name: 'Brightest Flame', color: 'Event', rarity: 'Ancient', type: 'Skill' },
  'CARD.BUBBLE_BUBBLE': { name: 'Bubble Bubble', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.BUFFER': { name: 'Buffer', color: 'Defect', rarity: 'Rare', type: 'Power' },
  'CARD.BULK_UP': { name: 'Bulk Up', color: 'Defect', rarity: 'Uncommon', type: 'Power' },
  'CARD.BULLET_TIME': { name: 'Bullet Time', color: 'Silent', rarity: 'Rare', type: 'Skill' },
  'CARD.BULLY': { name: 'Bully', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.BULWARK': { name: 'Bulwark', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.BUNDLE_OF_JOY': { name: 'Bundle of Joy', color: 'Regent', rarity: 'Rare', type: 'Skill' },
  'CARD.BURN': { name: 'Burn', color: 'Status', rarity: 'Status', type: 'Status' },
  'CARD.BURNING_PACT': { name: 'Burning Pact', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.BURST': { name: 'Burst', color: 'Silent', rarity: 'Rare', type: 'Skill' },
  'CARD.BURY': { name: 'Bury', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack' },
  'CARD.BYRD_SWOOP': { name: 'Byrd Swoop', color: 'Event', rarity: 'Event', type: 'Attack' },
  'CARD.BYRDONIS_EGG': { name: 'Byrdonis Egg', color: 'Quest', rarity: 'Quest', type: 'Quest' },
  'CARD.CHARGE': { name: 'CHARGE!!', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.CALAMITY': { name: 'Calamity', color: 'Colorless', rarity: 'Rare', type: 'Power' },
  'CARD.CALCIFY': { name: 'Calcify', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power' },
  'CARD.CALCULATED_GAMBLE': { name: 'Calculated Gamble', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.CALL_OF_THE_VOID': { name: 'Call of the Void', color: 'Necrobinder', rarity: 'Rare', type: 'Power' },
  'CARD.CALTROPS': { name: 'Caltrops', color: 'Event', rarity: 'Event', type: 'Power' },
  'CARD.CAPACITOR': { name: 'Capacitor', color: 'Defect', rarity: 'Uncommon', type: 'Power' },
  'CARD.CAPTURE_SPIRIT': { name: 'Capture Spirit', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.CASCADE': { name: 'Cascade', color: 'Ironclad', rarity: 'Rare', type: 'Skill' },
  'CARD.CATASTROPHE': { name: 'Catastrophe', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.CELESTIAL_MIGHT': { name: 'Celestial Might', color: 'Regent', rarity: 'Common', type: 'Attack' },
  'CARD.CHAOS': { name: 'Chaos', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.CHARGE_BATTERY': { name: 'Charge Battery', color: 'Defect', rarity: 'Common', type: 'Skill' },
  'CARD.CHILD_OF_THE_STARS': { name: 'Child of the Stars', color: 'Regent', rarity: 'Uncommon', type: 'Power' },
  'CARD.CHILL': { name: 'Chill', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.CINDER': { name: 'Cinder', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.CLASH': { name: 'Clash', color: 'Event', rarity: 'Event', type: 'Attack' },
  'CARD.CLAW': { name: 'Claw', color: 'Defect', rarity: 'Common', type: 'Attack' },
  'CARD.CLEANSE': { name: 'Cleanse', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.CLOAK_AND_DAGGER': { name: 'Cloak and Dagger', color: 'Silent', rarity: 'Common', type: 'Skill' },
  'CARD.CLOAK_OF_STARS': { name: 'Cloak of Stars', color: 'Regent', rarity: 'Common', type: 'Skill' },
  'CARD.CLUMSY': { name: 'Clumsy', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.COLD_SNAP': { name: 'Cold Snap', color: 'Defect', rarity: 'Common', type: 'Attack' },
  'CARD.COLLISION_COURSE': { name: 'Collision Course', color: 'Regent', rarity: 'Common', type: 'Attack' },
  'CARD.COLOSSUS': { name: 'Colossus', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.COMET': { name: 'Comet', color: 'Regent', rarity: 'Rare', type: 'Attack' },
  'CARD.COMPACT': { name: 'Compact', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.COMPILE_DRIVER': { name: 'Compile Driver', color: 'Defect', rarity: 'Common', type: 'Attack' },
  'CARD.CONFLAGRATION': { name: 'Conflagration', color: 'Ironclad', rarity: 'Rare', type: 'Attack' },
  'CARD.CONQUEROR': { name: 'Conqueror', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.CONSUMING_SHADOW': { name: 'Consuming Shadow', color: 'Defect', rarity: 'Rare', type: 'Power' },
  'CARD.CONVERGENCE': { name: 'Convergence', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.COOLANT': { name: 'Coolant', color: 'Defect', rarity: 'Rare', type: 'Power' },
  'CARD.COOLHEADED': { name: 'Coolheaded', color: 'Defect', rarity: 'Common', type: 'Skill' },
  'CARD.COORDINATE': { name: 'Coordinate', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.CORROSIVE_WAVE': { name: 'Corrosive Wave', color: 'Silent', rarity: 'Rare', type: 'Skill' },
  'CARD.CORRUPTION': { name: 'Corruption', color: 'Ironclad', rarity: 'Ancient', type: 'Power' },
  'CARD.COSMIC_INDIFFERENCE': { name: 'Cosmic Indifference', color: 'Regent', rarity: 'Common', type: 'Skill' },
  'CARD.COUNTDOWN': { name: 'Countdown', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power' },
  'CARD.CRASH_LANDING': { name: 'Crash Landing', color: 'Regent', rarity: 'Rare', type: 'Attack' },
  'CARD.CREATIVE_AI': { name: 'Creative AI', color: 'Defect', rarity: 'Rare', type: 'Power' },
  'CARD.CRESCENT_SPEAR': { name: 'Crescent Spear', color: 'Regent', rarity: 'Common', type: 'Attack' },
  'CARD.CRIMSON_MANTLE': { name: 'Crimson Mantle', color: 'Ironclad', rarity: 'Rare', type: 'Power' },
  'CARD.CRUELTY': { name: 'Cruelty', color: 'Ironclad', rarity: 'Rare', type: 'Power' },
  'CARD.CRUSH_UNDER': { name: 'Crush Under', color: 'Regent', rarity: 'Common', type: 'Attack' },
  'CARD.CURSE_OF_THE_BELL': { name: 'Curse of the Bell', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.DAGGER_SPRAY': { name: 'Dagger Spray', color: 'Silent', rarity: 'Common', type: 'Attack' },
  'CARD.DAGGER_THROW': { name: 'Dagger Throw', color: 'Silent', rarity: 'Common', type: 'Attack' },
  'CARD.DANSE_MACABRE': { name: 'Danse Macabre', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power' },
  'CARD.DARK_EMBRACE': { name: 'Dark Embrace', color: 'Ironclad', rarity: 'Rare', type: 'Power' },
  'CARD.DARK_SHACKLES': { name: 'Dark Shackles', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.DARKNESS': { name: 'Darkness', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.DASH': { name: 'Dash', color: 'Silent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.DAZED': { name: 'Dazed', color: 'Status', rarity: 'Status', type: 'Status' },
  'CARD.DEADLY_POISON': { name: 'Deadly Poison', color: 'Silent', rarity: 'Common', type: 'Skill' },
  'CARD.DEATH_MARCH': { name: 'Death March', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack' },
  'CARD.DEATHS_DOOR': { name: 'Death\'s Door', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.DEATHBRINGER': { name: 'Deathbringer', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.DEBILITATE': { name: 'Debilitate', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack' },
  'CARD.DEBRIS': { name: 'Debris', color: 'Status', rarity: 'Status', type: 'Status' },
  'CARD.DEBT': { name: 'Debt', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.DECAY': { name: 'Decay', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.DECISIONS_DECISIONS': { name: 'Decisions, Decisions', color: 'Regent', rarity: 'Rare', type: 'Skill' },
  'CARD.DEFEND_IRONCLAD': { name: 'Defend', color: 'Ironclad', rarity: 'Basic', type: 'Skill' },
  'CARD.DEFEND_SILENT': { name: 'Defend', color: 'Silent', rarity: 'Basic', type: 'Skill' },
  'CARD.DEFEND_REGENT': { name: 'Defend', color: 'Regent', rarity: 'Basic', type: 'Skill' },
  'CARD.DEFEND_NECROBINDER': { name: 'Defend', color: 'Necrobinder', rarity: 'Basic', type: 'Skill' },
  'CARD.DEFEND_DEFECT': { name: 'Defend', color: 'Defect', rarity: 'Basic', type: 'Skill' },
  'CARD.DEFILE': { name: 'Defile', color: 'Necrobinder', rarity: 'Common', type: 'Attack' },
  'CARD.DEFLECT': { name: 'Deflect', color: 'Silent', rarity: 'Common', type: 'Skill' },
  'CARD.DEFRAGMENT': { name: 'Defragment', color: 'Defect', rarity: 'Rare', type: 'Power' },
  'CARD.DEFY': { name: 'Defy', color: 'Necrobinder', rarity: 'Common', type: 'Skill' },
  'CARD.DELAY': { name: 'Delay', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.DEMESNE': { name: 'Demesne', color: 'Necrobinder', rarity: 'Rare', type: 'Power' },
  'CARD.DEMON_FORM': { name: 'Demon Form', color: 'Ironclad', rarity: 'Rare', type: 'Power' },
  'CARD.DEMONIC_SHIELD': { name: 'Demonic Shield', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.DEVASTATE': { name: 'Devastate', color: 'Regent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.DEVOUR_LIFE': { name: 'Devour Life', color: 'Necrobinder', rarity: 'Rare', type: 'Power' },
  'CARD.DIRGE': { name: 'Dirge', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.DISCOVERY': { name: 'Discovery', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.DISINTEGRATION': { name: 'Disintegration', color: 'Token', rarity: 'Status', type: 'Status' },
  'CARD.DISMANTLE': { name: 'Dismantle', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.DISTRACTION': { name: 'Distraction', color: 'Event', rarity: 'Event', type: 'Skill' },
  'CARD.DODGE_AND_ROLL': { name: 'Dodge and Roll', color: 'Silent', rarity: 'Common', type: 'Skill' },
  'CARD.DOMINATE': { name: 'Dominate', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.DOUBLE_ENERGY': { name: 'Double Energy', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.DOUBT': { name: 'Doubt', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.DRAIN_POWER': { name: 'Drain Power', color: 'Necrobinder', rarity: 'Common', type: 'Attack' },
  'CARD.DRAMATIC_ENTRANCE': { name: 'Dramatic Entrance', color: 'Colorless', rarity: 'Uncommon', type: 'Attack' },
  'CARD.DREDGE': { name: 'Dredge', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.DRUM_OF_BATTLE': { name: 'Drum of Battle', color: 'Ironclad', rarity: 'Uncommon', type: 'Power' },
  'CARD.DUAL_WIELD': { name: 'Dual Wield', color: 'Event', rarity: 'Event', type: 'Skill' },
  'CARD.DUALCAST': { name: 'Dualcast', color: 'Defect', rarity: 'Basic', type: 'Skill' },
  'CARD.DYING_STAR': { name: 'Dying Star', color: 'Regent', rarity: 'Rare', type: 'Attack' },
  'CARD.ECHO_FORM': { name: 'Echo Form', color: 'Defect', rarity: 'Rare', type: 'Power' },
  'CARD.ECHOING_SLASH': { name: 'Echoing Slash', color: 'Silent', rarity: 'Rare', type: 'Attack' },
  'CARD.EIDOLON': { name: 'Eidolon', color: 'Necrobinder', rarity: 'Rare', type: 'Skill' },
  'CARD.END_OF_DAYS': { name: 'End of Days', color: 'Necrobinder', rarity: 'Rare', type: 'Skill' },
  'CARD.ENERGY_SURGE': { name: 'Energy Surge', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.ENFEEBLING_TOUCH': { name: 'Enfeebling Touch', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.ENLIGHTENMENT': { name: 'Enlightenment', color: 'Event', rarity: 'Event', type: 'Skill' },
  'CARD.ENTHRALLED': { name: 'Enthralled', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.ENTRENCH': { name: 'Entrench', color: 'Event', rarity: 'Event', type: 'Skill' },
  'CARD.ENTROPY': { name: 'Entropy', color: 'Colorless', rarity: 'Rare', type: 'Power' },
  'CARD.ENVENOM': { name: 'Envenom', color: 'Silent', rarity: 'Rare', type: 'Power' },
  'CARD.EQUILIBRIUM': { name: 'Equilibrium', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.ERADICATE': { name: 'Eradicate', color: 'Necrobinder', rarity: 'Rare', type: 'Attack' },
  'CARD.ESCAPE_PLAN': { name: 'Escape Plan', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.ETERNAL_ARMOR': { name: 'Eternal Armor', color: 'Colorless', rarity: 'Rare', type: 'Power' },
  'CARD.EVIL_EYE': { name: 'Evil Eye', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.EXPECT_A_FIGHT': { name: 'Expect a Fight', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.EXPERTISE': { name: 'Expertise', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.EXPOSE': { name: 'Expose', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.EXTERMINATE': { name: 'Exterminate', color: 'Event', rarity: 'Event', type: 'Attack' },
  'CARD.FTL': { name: 'FTL', color: 'Defect', rarity: 'Uncommon', type: 'Attack' },
  'CARD.FALLING_STAR': { name: 'Falling Star', color: 'Regent', rarity: 'Basic', type: 'Attack' },
  'CARD.FAN_OF_KNIVES': { name: 'Fan of Knives', color: 'Silent', rarity: 'Rare', type: 'Power' },
  'CARD.FASTEN': { name: 'Fasten', color: 'Colorless', rarity: 'Uncommon', type: 'Power' },
  'CARD.FEAR': { name: 'Fear', color: 'Necrobinder', rarity: 'Common', type: 'Attack' },
  'CARD.FEED': { name: 'Feed', color: 'Ironclad', rarity: 'Rare', type: 'Attack' },
  'CARD.FEEDING_FRENZY': { name: 'Feeding Frenzy', color: 'Event', rarity: 'Event', type: 'Skill' },
  'CARD.FEEL_NO_PAIN': { name: 'Feel No Pain', color: 'Ironclad', rarity: 'Uncommon', type: 'Power' },
  'CARD.FERAL': { name: 'Feral', color: 'Defect', rarity: 'Uncommon', type: 'Power' },
  'CARD.FETCH': { name: 'Fetch', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack' },
  'CARD.FIEND_FIRE': { name: 'Fiend Fire', color: 'Ironclad', rarity: 'Rare', type: 'Attack' },
  'CARD.FIGHT_ME': { name: 'Fight Me!', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.FIGHT_THROUGH': { name: 'Fight Through', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.FINESSE': { name: 'Finesse', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.FINISHER': { name: 'Finisher', color: 'Silent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.FISTICUFFS': { name: 'Fisticuffs', color: 'Colorless', rarity: 'Uncommon', type: 'Attack' },
  'CARD.FLAK_CANNON': { name: 'Flak Cannon', color: 'Defect', rarity: 'Rare', type: 'Attack' },
  'CARD.FLAME_BARRIER': { name: 'Flame Barrier', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.FLANKING': { name: 'Flanking', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.FLASH_OF_STEEL': { name: 'Flash of Steel', color: 'Colorless', rarity: 'Uncommon', type: 'Attack' },
  'CARD.FLATTEN': { name: 'Flatten', color: 'Necrobinder', rarity: 'Common', type: 'Attack' },
  'CARD.FLECHETTES': { name: 'Flechettes', color: 'Silent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.FLICK_FLACK': { name: 'Flick-Flack', color: 'Silent', rarity: 'Common', type: 'Attack' },
  'CARD.FOCUSED_STRIKE': { name: 'Focused Strike', color: 'Defect', rarity: 'Common', type: 'Attack' },
  'CARD.FOLLOW_THROUGH': { name: 'Follow Through', color: 'Silent', rarity: 'Common', type: 'Attack' },
  'CARD.FOLLY': { name: 'Folly', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.FOOTWORK': { name: 'Footwork', color: 'Silent', rarity: 'Uncommon', type: 'Power' },
  'CARD.FORBIDDEN_GRIMOIRE': { name: 'Forbidden Grimoire', color: 'Necrobinder', rarity: 'Ancient', type: 'Power' },
  'CARD.FOREGONE_CONCLUSION': { name: 'Foregone Conclusion', color: 'Regent', rarity: 'Rare', type: 'Skill' },
  'CARD.FORGOTTEN_RITUAL': { name: 'Forgotten Ritual', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.FRANTIC_ESCAPE': { name: 'Frantic Escape', color: 'Status', rarity: 'Status', type: 'Status' },
  'CARD.FRIENDSHIP': { name: 'Friendship', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power' },
  'CARD.FUEL': { name: 'Fuel', color: 'Token', rarity: 'Token', type: 'Skill' },
  'CARD.FURNACE': { name: 'Furnace', color: 'Regent', rarity: 'Uncommon', type: 'Power' },
  'CARD.FUSION': { name: 'Fusion', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.GUARDS': { name: 'GUARDS!!!', color: 'Regent', rarity: 'Rare', type: 'Skill' },
  'CARD.GAMMA_BLAST': { name: 'Gamma Blast', color: 'Regent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.GANG_UP': { name: 'Gang Up', color: 'Colorless', rarity: 'Uncommon', type: 'Attack' },
  'CARD.GATHER_LIGHT': { name: 'Gather Light', color: 'Regent', rarity: 'Common', type: 'Skill' },
  'CARD.GENESIS': { name: 'Genesis', color: 'Regent', rarity: 'Rare', type: 'Power' },
  'CARD.GENETIC_ALGORITHM': { name: 'Genetic Algorithm', color: 'Defect', rarity: 'Rare', type: 'Skill' },
  'CARD.GIANT_ROCK': { name: 'Giant Rock', color: 'Token', rarity: 'Token', type: 'Attack' },
  'CARD.GLACIER': { name: 'Glacier', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.GLASSWORK': { name: 'Glasswork', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.GLIMMER': { name: 'Glimmer', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.GLIMPSE_BEYOND': { name: 'Glimpse Beyond', color: 'Necrobinder', rarity: 'Rare', type: 'Skill' },
  'CARD.GLITTERSTREAM': { name: 'Glitterstream', color: 'Regent', rarity: 'Common', type: 'Skill' },
  'CARD.GLOW': { name: 'Glow', color: 'Regent', rarity: 'Common', type: 'Skill' },
  'CARD.GO_FOR_THE_EYES': { name: 'Go for the Eyes', color: 'Defect', rarity: 'Common', type: 'Attack' },
  'CARD.GOLD_AXE': { name: 'Gold Axe', color: 'Colorless', rarity: 'Rare', type: 'Attack' },
  'CARD.GRAND_FINALE': { name: 'Grand Finale', color: 'Silent', rarity: 'Rare', type: 'Attack' },
  'CARD.GRAPPLE': { name: 'Grapple', color: 'Unknown', rarity: 'Uncommon', type: 'Attack' },
  'CARD.GRAVE_WARDEN': { name: 'Grave Warden', color: 'Necrobinder', rarity: 'Common', type: 'Skill' },
  'CARD.GRAVEBLAST': { name: 'Graveblast', color: 'Necrobinder', rarity: 'Common', type: 'Attack' },
  'CARD.GREED': { name: 'Greed', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.GUIDING_STAR': { name: 'Guiding Star', color: 'Regent', rarity: 'Common', type: 'Attack' },
  'CARD.GUILTY': { name: 'Guilty', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.GUNK_UP': { name: 'Gunk Up', color: 'Defect', rarity: 'Common', type: 'Attack' },
  'CARD.HAILSTORM': { name: 'Hailstorm', color: 'Defect', rarity: 'Uncommon', type: 'Power' },
  'CARD.HAMMER_TIME': { name: 'Hammer Time', color: 'Regent', rarity: 'Rare', type: 'Power' },
  'CARD.HAND_TRICK': { name: 'Hand Trick', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.HAND_OF_GREED': { name: 'Hand of Greed', color: 'Colorless', rarity: 'Rare', type: 'Attack' },
  'CARD.HANG': { name: 'Hang', color: 'Necrobinder', rarity: 'Rare', type: 'Attack' },
  'CARD.HAUNT': { name: 'Haunt', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power' },
  'CARD.HAVOC': { name: 'Havoc', color: 'Ironclad', rarity: 'Common', type: 'Skill' },
  'CARD.HAZE': { name: 'Haze', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.HEADBUTT': { name: 'Headbutt', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.HEAVENLY_DRILL': { name: 'Heavenly Drill', color: 'Regent', rarity: 'Rare', type: 'Attack' },
  'CARD.HEGEMONY': { name: 'Hegemony', color: 'Regent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.HEIRLOOM_HAMMER': { name: 'Heirloom Hammer', color: 'Regent', rarity: 'Rare', type: 'Attack' },
  'CARD.HELIX_DRILL': { name: 'Helix Drill', color: 'Defect', rarity: 'Rare', type: 'Attack' },
  'CARD.HELLO_WORLD': { name: 'Hello World', color: 'Event', rarity: 'Event', type: 'Power' },
  'CARD.HELLRAISER': { name: 'Hellraiser', color: 'Ironclad', rarity: 'Rare', type: 'Power' },
  'CARD.HEMOKINESIS': { name: 'Hemokinesis', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.HIDDEN_CACHE': { name: 'Hidden Cache', color: 'Regent', rarity: 'Common', type: 'Skill' },
  'CARD.HIDDEN_DAGGERS': { name: 'Hidden Daggers', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.HIDDEN_GEM': { name: 'Hidden Gem', color: 'Colorless', rarity: 'Rare', type: 'Skill' },
  'CARD.HIGH_FIVE': { name: 'High Five', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack' },
  'CARD.HOLOGRAM': { name: 'Hologram', color: 'Defect', rarity: 'Common', type: 'Skill' },
  'CARD.HOTFIX': { name: 'Hotfix', color: 'Defect', rarity: 'Common', type: 'Skill' },
  'CARD.HOWL_FROM_BEYOND': { name: 'Howl from Beyond', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.HUDDLE_UP': { name: 'Huddle Up', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.HYPERBEAM': { name: 'Hyperbeam', color: 'Defect', rarity: 'Rare', type: 'Attack' },
  'CARD.I_AM_INVINCIBLE': { name: 'I Am Invincible', color: 'Regent', rarity: 'Rare', type: 'Skill' },
  'CARD.ICE_LANCE': { name: 'Ice Lance', color: 'Defect', rarity: 'Rare', type: 'Attack' },
  'CARD.IGNITION': { name: 'Ignition', color: 'Defect', rarity: 'Rare', type: 'Skill' },
  'CARD.IMPATIENCE': { name: 'Impatience', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.IMPERVIOUS': { name: 'Impervious', color: 'Ironclad', rarity: 'Rare', type: 'Skill' },
  'CARD.INFECTION': { name: 'Infection', color: 'Status', rarity: 'Status', type: 'Status' },
  'CARD.INFERNAL_BLADE': { name: 'Infernal Blade', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.INFERNO': { name: 'Inferno', color: 'Ironclad', rarity: 'Uncommon', type: 'Power' },
  'CARD.INFINITE_BLADES': { name: 'Infinite Blades', color: 'Silent', rarity: 'Uncommon', type: 'Power' },
  'CARD.INFLAME': { name: 'Inflame', color: 'Ironclad', rarity: 'Uncommon', type: 'Power' },
  'CARD.INJURY': { name: 'Injury', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.INTERCEPT': { name: 'Intercept', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.INVOKE': { name: 'Invoke', color: 'Necrobinder', rarity: 'Common', type: 'Skill' },
  'CARD.IRON_WAVE': { name: 'Iron Wave', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.ITERATION': { name: 'Iteration', color: 'Defect', rarity: 'Uncommon', type: 'Power' },
  'CARD.JACK_OF_ALL_TRADES': { name: 'Jack of All Trades', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.JACKPOT': { name: 'Jackpot', color: 'Colorless', rarity: 'Rare', type: 'Attack' },
  'CARD.JUGGERNAUT': { name: 'Juggernaut', color: 'Ironclad', rarity: 'Rare', type: 'Power' },
  'CARD.JUGGLING': { name: 'Juggling', color: 'Ironclad', rarity: 'Uncommon', type: 'Power' },
  'CARD.KINGLY_KICK': { name: 'Kingly Kick', color: 'Regent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.KINGLY_PUNCH': { name: 'Kingly Punch', color: 'Regent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.KNIFE_TRAP': { name: 'Knife Trap', color: 'Silent', rarity: 'Rare', type: 'Skill' },
  'CARD.KNOCKDOWN': { name: 'Knockdown', color: 'Colorless', rarity: 'Rare', type: 'Attack' },
  'CARD.KNOCKOUT_BLOW': { name: 'Knockout Blow', color: 'Regent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.KNOW_THY_PLACE': { name: 'Know Thy Place', color: 'Regent', rarity: 'Common', type: 'Skill' },
  'CARD.LANTERN_KEY': { name: 'Lantern Key', color: 'Quest', rarity: 'Quest', type: 'Quest' },
  'CARD.LARGESSE': { name: 'Largesse', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.LEADING_STRIKE': { name: 'Leading Strike', color: 'Silent', rarity: 'Common', type: 'Attack' },
  'CARD.LEAP': { name: 'Leap', color: 'Defect', rarity: 'Common', type: 'Skill' },
  'CARD.LEG_SWEEP': { name: 'Leg Sweep', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.LEGION_OF_BONE': { name: 'Legion of Bone', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.LETHALITY': { name: 'Lethality', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power' },
  'CARD.LIFT': { name: 'Lift', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.LIGHTNING_ROD': { name: 'Lightning Rod', color: 'Defect', rarity: 'Common', type: 'Skill' },
  'CARD.LOOP': { name: 'Loop', color: 'Defect', rarity: 'Uncommon', type: 'Power' },
  'CARD.LUMINESCE': { name: 'Luminesce', color: 'Token', rarity: 'Token', type: 'Skill' },
  'CARD.LUNAR_BLAST': { name: 'Lunar Blast', color: 'Regent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.MACHINE_LEARNING': { name: 'Machine Learning', color: 'Defect', rarity: 'Rare', type: 'Power' },
  'CARD.MAD_SCIENCE': { name: 'Mad Science', color: 'Event', rarity: 'Event', type: 'Attack' },
  'CARD.MAKE_IT_SO': { name: 'Make It So', color: 'Regent', rarity: 'Rare', type: 'Attack' },
  'CARD.MALAISE': { name: 'Malaise', color: 'Silent', rarity: 'Rare', type: 'Skill' },
  'CARD.MANGLE': { name: 'Mangle', color: 'Ironclad', rarity: 'Rare', type: 'Attack' },
  'CARD.MANIFEST_AUTHORITY': { name: 'Manifest Authority', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.MASTER_PLANNER': { name: 'Master Planner', color: 'Silent', rarity: 'Rare', type: 'Power' },
  'CARD.MASTER_OF_STRATEGY': { name: 'Master of Strategy', color: 'Colorless', rarity: 'Rare', type: 'Skill' },
  'CARD.MAUL': { name: 'Maul', color: 'Event', rarity: 'Ancient', type: 'Attack' },
  'CARD.MAYHEM': { name: 'Mayhem', color: 'Colorless', rarity: 'Rare', type: 'Power' },
  'CARD.MELANCHOLY': { name: 'Melancholy', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.MEMENTO_MORI': { name: 'Memento Mori', color: 'Silent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.METAMORPHOSIS': { name: 'Metamorphosis', color: 'Event', rarity: 'Event', type: 'Skill' },
  'CARD.METEOR_SHOWER': { name: 'Meteor Shower', color: 'Regent', rarity: 'Ancient', type: 'Attack' },
  'CARD.METEOR_STRIKE': { name: 'Meteor Strike', color: 'Defect', rarity: 'Rare', type: 'Attack' },
  'CARD.MIMIC': { name: 'Mimic', color: 'Colorless', rarity: 'Rare', type: 'Skill' },
  'CARD.MIND_BLAST': { name: 'Mind Blast', color: 'Colorless', rarity: 'Uncommon', type: 'Attack' },
  'CARD.MIND_ROT': { name: 'Mind Rot', color: 'Token', rarity: 'Status', type: 'Status' },
  'CARD.MINION_DIVE_BOMB': { name: 'Minion Dive Bomb', color: 'Token', rarity: 'Token', type: 'Attack' },
  'CARD.MINION_SACRIFICE': { name: 'Minion Sacrifice', color: 'Token', rarity: 'Token', type: 'Skill' },
  'CARD.MINION_STRIKE': { name: 'Minion Strike', color: 'Token', rarity: 'Token', type: 'Attack' },
  'CARD.MIRAGE': { name: 'Mirage', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.MISERY': { name: 'Misery', color: 'Necrobinder', rarity: 'Rare', type: 'Attack' },
  'CARD.MODDED': { name: 'Modded', color: 'Defect', rarity: 'Rare', type: 'Skill' },
  'CARD.MOLTEN_FIST': { name: 'Molten Fist', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.MOMENTUM_STRIKE': { name: 'Momentum Strike', color: 'Defect', rarity: 'Common', type: 'Attack' },
  'CARD.MONARCHS_GAZE': { name: 'Monarch\'s Gaze', color: 'Regent', rarity: 'Rare', type: 'Power' },
  'CARD.MONOLOGUE': { name: 'Monologue', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.MULTI_CAST': { name: 'Multi-Cast', color: 'Defect', rarity: 'Rare', type: 'Skill' },
  'CARD.MURDER': { name: 'Murder', color: 'Silent', rarity: 'Rare', type: 'Attack' },
  'CARD.NECRO_MASTERY': { name: 'Necro Mastery', color: 'Necrobinder', rarity: 'Rare', type: 'Power' },
  'CARD.NEGATIVE_PULSE': { name: 'Negative Pulse', color: 'Necrobinder', rarity: 'Common', type: 'Skill' },
  'CARD.NEOWS_FURY': { name: 'Neow\'s Fury', color: 'Event', rarity: 'Ancient', type: 'Attack' },
  'CARD.NEUROSURGE': { name: 'Neurosurge', color: 'Necrobinder', rarity: 'Rare', type: 'Power' },
  'CARD.NEUTRALIZE': { name: 'Neutralize', color: 'Silent', rarity: 'Basic', type: 'Attack' },
  'CARD.NEUTRON_AEGIS': { name: 'Neutron Aegis', color: 'Regent', rarity: 'Rare', type: 'Power' },
  'CARD.NIGHTMARE': { name: 'Nightmare', color: 'Silent', rarity: 'Rare', type: 'Skill' },
  'CARD.NO_ESCAPE': { name: 'No Escape', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.NORMALITY': { name: 'Normality', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.NOSTALGIA': { name: 'Nostalgia', color: 'Colorless', rarity: 'Rare', type: 'Power' },
  'CARD.NOT_YET': { name: 'Not Yet', color: 'Ironclad', rarity: 'Rare', type: 'Skill' },
  'CARD.NOXIOUS_FUMES': { name: 'Noxious Fumes', color: 'Silent', rarity: 'Uncommon', type: 'Power' },
  'CARD.NULL': { name: 'Null', color: 'Defect', rarity: 'Uncommon', type: 'Attack' },
  'CARD.OBLIVION': { name: 'Oblivion', color: 'Necrobinder', rarity: 'Rare', type: 'Skill' },
  'CARD.OFFERING': { name: 'Offering', color: 'Ironclad', rarity: 'Rare', type: 'Skill' },
  'CARD.OMNISLICE': { name: 'Omnislice', color: 'Colorless', rarity: 'Uncommon', type: 'Attack' },
  'CARD.ONE_TWO_PUNCH': { name: 'One-Two Punch', color: 'Ironclad', rarity: 'Rare', type: 'Skill' },
  'CARD.ORBIT': { name: 'Orbit', color: 'Regent', rarity: 'Uncommon', type: 'Power' },
  'CARD.OUTBREAK': { name: 'Outbreak', color: 'Silent', rarity: 'Uncommon', type: 'Power' },
  'CARD.OUTMANEUVER': { name: 'Outmaneuver', color: 'Event', rarity: 'Event', type: 'Skill' },
  'CARD.OVERCLOCK': { name: 'Overclock', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.PACTS_END': { name: 'Pact\'s End', color: 'Ironclad', rarity: 'Rare', type: 'Attack' },
  'CARD.PAGESTORM': { name: 'Pagestorm', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power' },
  'CARD.PALE_BLUE_DOT': { name: 'Pale Blue Dot', color: 'Regent', rarity: 'Uncommon', type: 'Power' },
  'CARD.PANACHE': { name: 'Panache', color: 'Colorless', rarity: 'Uncommon', type: 'Power' },
  'CARD.PANIC_BUTTON': { name: 'Panic Button', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.PARRY': { name: 'Parry', color: 'Regent', rarity: 'Uncommon', type: 'Power' },
  'CARD.PARSE': { name: 'Parse', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.PARTICLE_WALL': { name: 'Particle Wall', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.PATTER': { name: 'Patter', color: 'Regent', rarity: 'Common', type: 'Skill' },
  'CARD.PECK': { name: 'Peck', color: 'Event', rarity: 'Event', type: 'Attack' },
  'CARD.PERFECTED_STRIKE': { name: 'Perfected Strike', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.PHANTOM_BLADES': { name: 'Phantom Blades', color: 'Silent', rarity: 'Uncommon', type: 'Power' },
  'CARD.PHOTON_CUT': { name: 'Photon Cut', color: 'Regent', rarity: 'Common', type: 'Attack' },
  'CARD.PIERCING_WAIL': { name: 'Piercing Wail', color: 'Silent', rarity: 'Common', type: 'Skill' },
  'CARD.PILLAGE': { name: 'Pillage', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.PILLAR_OF_CREATION': { name: 'Pillar of Creation', color: 'Regent', rarity: 'Uncommon', type: 'Power' },
  'CARD.PINPOINT': { name: 'Pinpoint', color: 'Silent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.POISONED_STAB': { name: 'Poisoned Stab', color: 'Silent', rarity: 'Common', type: 'Attack' },
  'CARD.POKE': { name: 'Poke', color: 'Necrobinder', rarity: 'Common', type: 'Attack' },
  'CARD.POMMEL_STRIKE': { name: 'Pommel Strike', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.POOR_SLEEP': { name: 'Poor Sleep', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.POUNCE': { name: 'Pounce', color: 'Silent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.PRECISE_CUT': { name: 'Precise Cut', color: 'Silent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.PREDATOR': { name: 'Predator', color: 'Silent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.PREP_TIME': { name: 'Prep Time', color: 'Colorless', rarity: 'Uncommon', type: 'Power' },
  'CARD.PREPARED': { name: 'Prepared', color: 'Silent', rarity: 'Common', type: 'Skill' },
  'CARD.PRIMAL_FORCE': { name: 'Primal Force', color: 'Ironclad', rarity: 'Rare', type: 'Skill' },
  'CARD.PRODUCTION': { name: 'Production', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.PROLONG': { name: 'Prolong', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.PROPHESIZE': { name: 'Prophesize', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.PROTECTOR': { name: 'Protector', color: 'Necrobinder', rarity: 'Ancient', type: 'Attack' },
  'CARD.PROWESS': { name: 'Prowess', color: 'Colorless', rarity: 'Uncommon', type: 'Power' },
  'CARD.PULL_AGGRO': { name: 'Pull Aggro', color: 'Necrobinder', rarity: 'Common', type: 'Skill' },
  'CARD.PULL_FROM_BELOW': { name: 'Pull from Below', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack' },
  'CARD.PURITY': { name: 'Purity', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.PUTREFY': { name: 'Putrefy', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.PYRE': { name: 'Pyre', color: 'Ironclad', rarity: 'Rare', type: 'Power' },
  'CARD.QUADCAST': { name: 'Quadcast', color: 'Defect', rarity: 'Ancient', type: 'Skill' },
  'CARD.QUASAR': { name: 'Quasar', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.RADIATE': { name: 'Radiate', color: 'Regent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.RAGE': { name: 'Rage', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.RAINBOW': { name: 'Rainbow', color: 'Defect', rarity: 'Rare', type: 'Skill' },
  'CARD.RALLY': { name: 'Rally', color: 'Colorless', rarity: 'Rare', type: 'Skill' },
  'CARD.RAMPAGE': { name: 'Rampage', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.RATTLE': { name: 'Rattle', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack' },
  'CARD.REANIMATE': { name: 'Reanimate', color: 'Necrobinder', rarity: 'Rare', type: 'Skill' },
  'CARD.REAP': { name: 'Reap', color: 'Necrobinder', rarity: 'Common', type: 'Attack' },
  'CARD.REAPER_FORM': { name: 'Reaper Form', color: 'Necrobinder', rarity: 'Rare', type: 'Power' },
  'CARD.REAVE': { name: 'Reave', color: 'Necrobinder', rarity: 'Common', type: 'Attack' },
  'CARD.REBOOT': { name: 'Reboot', color: 'Defect', rarity: 'Rare', type: 'Skill' },
  'CARD.REBOUND': { name: 'Rebound', color: 'Event', rarity: 'Event', type: 'Attack' },
  'CARD.REFINE_BLADE': { name: 'Refine Blade', color: 'Regent', rarity: 'Common', type: 'Skill' },
  'CARD.REFLECT': { name: 'Reflect', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.REFLEX': { name: 'Reflex', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.REFRACT': { name: 'Refract', color: 'Defect', rarity: 'Uncommon', type: 'Attack' },
  'CARD.REGRET': { name: 'Regret', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.RELAX': { name: 'Relax', color: 'Event', rarity: 'Ancient', type: 'Skill' },
  'CARD.REND': { name: 'Rend', color: 'Colorless', rarity: 'Rare', type: 'Attack' },
  'CARD.RESONANCE': { name: 'Resonance', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.RESTLESSNESS': { name: 'Restlessness', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.RICOCHET': { name: 'Ricochet', color: 'Silent', rarity: 'Common', type: 'Attack' },
  'CARD.RIGHT_HAND_HAND': { name: 'Right Hand Hand', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack' },
  'CARD.RIP_AND_TEAR': { name: 'Rip and Tear', color: 'Event', rarity: 'Event', type: 'Attack' },
  'CARD.ROCKET_PUNCH': { name: 'Rocket Punch', color: 'Defect', rarity: 'Uncommon', type: 'Attack' },
  'CARD.ROLLING_BOULDER': { name: 'Rolling Boulder', color: 'Colorless', rarity: 'Rare', type: 'Power' },
  'CARD.ROYAL_GAMBLE': { name: 'Royal Gamble', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.ROYALTIES': { name: 'Royalties', color: 'Regent', rarity: 'Rare', type: 'Power' },
  'CARD.RUPTURE': { name: 'Rupture', color: 'Ironclad', rarity: 'Uncommon', type: 'Power' },
  'CARD.SACRIFICE': { name: 'Sacrifice', color: 'Necrobinder', rarity: 'Rare', type: 'Skill' },
  'CARD.SALVO': { name: 'Salvo', color: 'Colorless', rarity: 'Rare', type: 'Attack' },
  'CARD.SCAVENGE': { name: 'Scavenge', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.SCOURGE': { name: 'Scourge', color: 'Necrobinder', rarity: 'Common', type: 'Skill' },
  'CARD.SCRAPE': { name: 'Scrape', color: 'Defect', rarity: 'Uncommon', type: 'Attack' },
  'CARD.SCRAWL': { name: 'Scrawl', color: 'Colorless', rarity: 'Rare', type: 'Skill' },
  'CARD.SCULPTING_STRIKE': { name: 'Sculpting Strike', color: 'Necrobinder', rarity: 'Common', type: 'Attack' },
  'CARD.SEANCE': { name: 'Seance', color: 'Necrobinder', rarity: 'Rare', type: 'Skill' },
  'CARD.SECOND_WIND': { name: 'Second Wind', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.SECRET_TECHNIQUE': { name: 'Secret Technique', color: 'Colorless', rarity: 'Rare', type: 'Skill' },
  'CARD.SECRET_WEAPON': { name: 'Secret Weapon', color: 'Colorless', rarity: 'Rare', type: 'Skill' },
  'CARD.SEEKER_STRIKE': { name: 'Seeker Strike', color: 'Colorless', rarity: 'Uncommon', type: 'Attack' },
  'CARD.SEEKING_EDGE': { name: 'Seeking Edge', color: 'Regent', rarity: 'Rare', type: 'Power' },
  'CARD.SENTRY_MODE': { name: 'Sentry Mode', color: 'Necrobinder', rarity: 'Rare', type: 'Power' },
  'CARD.SERPENT_FORM': { name: 'Serpent Form', color: 'Silent', rarity: 'Rare', type: 'Power' },
  'CARD.SETUP_STRIKE': { name: 'Setup Strike', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.SEVEN_STARS': { name: 'Seven Stars', color: 'Regent', rarity: 'Rare', type: 'Attack' },
  'CARD.SEVERANCE': { name: 'Severance', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack' },
  'CARD.SHADOW_SHIELD': { name: 'Shadow Shield', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.SHADOW_STEP': { name: 'Shadow Step', color: 'Silent', rarity: 'Rare', type: 'Skill' },
  'CARD.SHADOWMELD': { name: 'Shadowmeld', color: 'Silent', rarity: 'Rare', type: 'Skill' },
  'CARD.SHAME': { name: 'Shame', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.SHARED_FATE': { name: 'Shared Fate', color: 'Necrobinder', rarity: 'Rare', type: 'Skill' },
  'CARD.SHATTER': { name: 'Shatter', color: 'Defect', rarity: 'Rare', type: 'Attack' },
  'CARD.SHINING_STRIKE': { name: 'Shining Strike', color: 'Regent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.SHIV': { name: 'Shiv', color: 'Token', rarity: 'Token', type: 'Attack' },
  'CARD.SHOCKWAVE': { name: 'Shockwave', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.SHROUD': { name: 'Shroud', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power' },
  'CARD.SHRUG_IT_OFF': { name: 'Shrug It Off', color: 'Ironclad', rarity: 'Common', type: 'Skill' },
  'CARD.SIC_EM': { name: 'Sic \'Em', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack' },
  'CARD.SIGNAL_BOOST': { name: 'Signal Boost', color: 'Defect', rarity: 'Rare', type: 'Skill' },
  'CARD.SKEWER': { name: 'Skewer', color: 'Silent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.SKIM': { name: 'Skim', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.SLEIGHT_OF_FLESH': { name: 'Sleight of Flesh', color: 'Necrobinder', rarity: 'Uncommon', type: 'Power' },
  'CARD.SLICE': { name: 'Slice', color: 'Silent', rarity: 'Common', type: 'Attack' },
  'CARD.SLIMED': { name: 'Slimed', color: 'Status', rarity: 'Status', type: 'Status' },
  'CARD.SLOTH': { name: 'Sloth', color: 'Token', rarity: 'Status', type: 'Status' },
  'CARD.SMOKESTACK': { name: 'Smokestack', color: 'Defect', rarity: 'Uncommon', type: 'Power' },
  'CARD.SNAKEBITE': { name: 'Snakebite', color: 'Silent', rarity: 'Common', type: 'Skill' },
  'CARD.SNAP': { name: 'Snap', color: 'Necrobinder', rarity: 'Common', type: 'Attack' },
  'CARD.SNEAKY': { name: 'Sneaky', color: 'Silent', rarity: 'Rare', type: 'Power' },
  'CARD.SOLAR_STRIKE': { name: 'Solar Strike', color: 'Regent', rarity: 'Common', type: 'Attack' },
  'CARD.SOOT': { name: 'Soot', color: 'Status', rarity: 'Status', type: 'Status' },
  'CARD.SOUL': { name: 'Soul', color: 'Token', rarity: 'Token', type: 'Skill' },
  'CARD.SOUL_STORM': { name: 'Soul Storm', color: 'Necrobinder', rarity: 'Rare', type: 'Attack' },
  'CARD.SOVEREIGN_BLADE': { name: 'Sovereign Blade', color: 'Token', rarity: 'Token', type: 'Attack' },
  'CARD.SOW': { name: 'Sow', color: 'Necrobinder', rarity: 'Common', type: 'Attack' },
  'CARD.SPECTRUM_SHIFT': { name: 'Spectrum Shift', color: 'Regent', rarity: 'Uncommon', type: 'Power' },
  'CARD.SPEEDSTER': { name: 'Speedster', color: 'Silent', rarity: 'Uncommon', type: 'Power' },
  'CARD.SPINNER': { name: 'Spinner', color: 'Defect', rarity: 'Rare', type: 'Power' },
  'CARD.SPIRIT_OF_ASH': { name: 'Spirit of Ash', color: 'Necrobinder', rarity: 'Rare', type: 'Power' },
  'CARD.SPITE': { name: 'Spite', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.SPLASH': { name: 'Splash', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.SPOILS_MAP': { name: 'Spoils Map', color: 'Quest', rarity: 'Quest', type: 'Quest' },
  'CARD.SPOILS_OF_BATTLE': { name: 'Spoils of Battle', color: 'Regent', rarity: 'Common', type: 'Skill' },
  'CARD.SPORE_MIND': { name: 'Spore Mind', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.SPUR': { name: 'Spur', color: 'Necrobinder', rarity: 'Uncommon', type: 'Skill' },
  'CARD.SQUASH': { name: 'Squash', color: 'Event', rarity: 'Event', type: 'Attack' },
  'CARD.SQUEEZE': { name: 'Squeeze', color: 'Necrobinder', rarity: 'Rare', type: 'Attack' },
  'CARD.STACK': { name: 'Stack', color: 'Event', rarity: 'Event', type: 'Skill' },
  'CARD.STAMPEDE': { name: 'Stampede', color: 'Ironclad', rarity: 'Uncommon', type: 'Power' },
  'CARD.STARDUST': { name: 'Stardust', color: 'Regent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.STOKE': { name: 'Stoke', color: 'Ironclad', rarity: 'Rare', type: 'Skill' },
  'CARD.STOMP': { name: 'Stomp', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.STONE_ARMOR': { name: 'Stone Armor', color: 'Ironclad', rarity: 'Uncommon', type: 'Power' },
  'CARD.STORM': { name: 'Storm', color: 'Defect', rarity: 'Uncommon', type: 'Power' },
  'CARD.STORM_OF_STEEL': { name: 'Storm of Steel', color: 'Silent', rarity: 'Rare', type: 'Skill' },
  'CARD.STRANGLE': { name: 'Strangle', color: 'Silent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.STRATAGEM': { name: 'Stratagem', color: 'Colorless', rarity: 'Uncommon', type: 'Power' },
  'CARD.STRIKE_IRONCLAD': { name: 'Strike', color: 'Ironclad', rarity: 'Basic', type: 'Attack' },
  'CARD.STRIKE_SILENT': { name: 'Strike', color: 'Silent', rarity: 'Basic', type: 'Attack' },
  'CARD.STRIKE_REGENT': { name: 'Strike', color: 'Regent', rarity: 'Basic', type: 'Attack' },
  'CARD.STRIKE_NECROBINDER': { name: 'Strike', color: 'Necrobinder', rarity: 'Basic', type: 'Attack' },
  'CARD.STRIKE_DEFECT': { name: 'Strike', color: 'Defect', rarity: 'Basic', type: 'Attack' },
  'CARD.SUBROUTINE': { name: 'Subroutine', color: 'Defect', rarity: 'Uncommon', type: 'Power' },
  'CARD.SUCKER_PUNCH': { name: 'Sucker Punch', color: 'Silent', rarity: 'Common', type: 'Attack' },
  'CARD.SUMMON_FORTH': { name: 'Summon Forth', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.SUNDER': { name: 'Sunder', color: 'Defect', rarity: 'Uncommon', type: 'Attack' },
  'CARD.SUPERCRITICAL': { name: 'Supercritical', color: 'Defect', rarity: 'Rare', type: 'Skill' },
  'CARD.SUPERMASSIVE': { name: 'Supermassive', color: 'Regent', rarity: 'Uncommon', type: 'Attack' },
  'CARD.SUPPRESS': { name: 'Suppress', color: 'Silent', rarity: 'Ancient', type: 'Attack' },
  'CARD.SURVIVOR': { name: 'Survivor', color: 'Silent', rarity: 'Basic', type: 'Skill' },
  'CARD.SWEEPING_BEAM': { name: 'Sweeping Beam', color: 'Defect', rarity: 'Common', type: 'Attack' },
  'CARD.SWEEPING_GAZE': { name: 'Sweeping Gaze', color: 'Token', rarity: 'Token', type: 'Attack' },
  'CARD.SWORD_BOOMERANG': { name: 'Sword Boomerang', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.SWORD_SAGE': { name: 'Sword Sage', color: 'Regent', rarity: 'Rare', type: 'Power' },
  'CARD.SYNCHRONIZE': { name: 'Synchronize', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.SYNTHESIS': { name: 'Synthesis', color: 'Defect', rarity: 'Uncommon', type: 'Attack' },
  'CARD.TURBO': { name: 'TURBO', color: 'Defect', rarity: 'Common', type: 'Skill' },
  'CARD.TACTICIAN': { name: 'Tactician', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.TAG_TEAM': { name: 'Tag Team', color: 'Colorless', rarity: 'Uncommon', type: 'Attack' },
  'CARD.TANK': { name: 'Tank', color: 'Ironclad', rarity: 'Rare', type: 'Power' },
  'CARD.TAUNT': { name: 'Taunt', color: 'Ironclad', rarity: 'Uncommon', type: 'Skill' },
  'CARD.TEAR_ASUNDER': { name: 'Tear Asunder', color: 'Ironclad', rarity: 'Rare', type: 'Attack' },
  'CARD.TEMPEST': { name: 'Tempest', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.TERRAFORMING': { name: 'Terraforming', color: 'Regent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.TESLA_COIL': { name: 'Tesla Coil', color: 'Defect', rarity: 'Uncommon', type: 'Attack' },
  'CARD.THE_BOMB': { name: 'The Bomb', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.THE_GAMBIT': { name: 'The Gambit', color: 'Colorless', rarity: 'Rare', type: 'Skill' },
  'CARD.THE_HUNT': { name: 'The Hunt', color: 'Silent', rarity: 'Rare', type: 'Attack' },
  'CARD.THE_SCYTHE': { name: 'The Scythe', color: 'Necrobinder', rarity: 'Rare', type: 'Attack' },
  'CARD.THE_SEALED_THRONE': { name: 'The Sealed Throne', color: 'Regent', rarity: 'Ancient', type: 'Power' },
  'CARD.THE_SMITH': { name: 'The Smith', color: 'Regent', rarity: 'Rare', type: 'Skill' },
  'CARD.THINKING_AHEAD': { name: 'Thinking Ahead', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.THRASH': { name: 'Thrash', color: 'Ironclad', rarity: 'Rare', type: 'Attack' },
  'CARD.THRUMMING_HATCHET': { name: 'Thrumming Hatchet', color: 'Colorless', rarity: 'Uncommon', type: 'Attack' },
  'CARD.THUNDER': { name: 'Thunder', color: 'Defect', rarity: 'Uncommon', type: 'Power' },
  'CARD.THUNDERCLAP': { name: 'Thunderclap', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.TIMES_UP': { name: 'Time\'s Up', color: 'Necrobinder', rarity: 'Rare', type: 'Attack' },
  'CARD.TOOLS_OF_THE_TRADE': { name: 'Tools of the Trade', color: 'Silent', rarity: 'Rare', type: 'Power' },
  'CARD.TORIC_TOUGHNESS': { name: 'Toric Toughness', color: 'Event', rarity: 'Event', type: 'Skill' },
  'CARD.TOXIC': { name: 'Toxic', color: 'Status', rarity: 'Status', type: 'Status' },
  'CARD.TRACKING': { name: 'Tracking', color: 'Silent', rarity: 'Rare', type: 'Power' },
  'CARD.TRANSFIGURE': { name: 'Transfigure', color: 'Necrobinder', rarity: 'Rare', type: 'Skill' },
  'CARD.TRASH_TO_TREASURE': { name: 'Trash to Treasure', color: 'Defect', rarity: 'Rare', type: 'Power' },
  'CARD.TREMBLE': { name: 'Tremble', color: 'Ironclad', rarity: 'Common', type: 'Skill' },
  'CARD.TRUE_GRIT': { name: 'True Grit', color: 'Ironclad', rarity: 'Common', type: 'Skill' },
  'CARD.TWIN_STRIKE': { name: 'Twin Strike', color: 'Ironclad', rarity: 'Common', type: 'Attack' },
  'CARD.TYRANNY': { name: 'Tyranny', color: 'Regent', rarity: 'Rare', type: 'Power' },
  'CARD.ULTIMATE_DEFEND': { name: 'Ultimate Defend', color: 'Colorless', rarity: 'Uncommon', type: 'Skill' },
  'CARD.ULTIMATE_STRIKE': { name: 'Ultimate Strike', color: 'Colorless', rarity: 'Uncommon', type: 'Attack' },
  'CARD.UNDEATH': { name: 'Undeath', color: 'Necrobinder', rarity: 'Rare', type: 'Skill' },
  'CARD.UNLEASH': { name: 'Unleash', color: 'Necrobinder', rarity: 'Basic', type: 'Attack' },
  'CARD.UNMOVABLE': { name: 'Unmovable', color: 'Ironclad', rarity: 'Rare', type: 'Power' },
  'CARD.UNRELENTING': { name: 'Unrelenting', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.UNTOUCHABLE': { name: 'Untouchable', color: 'Silent', rarity: 'Common', type: 'Skill' },
  'CARD.UP_MY_SLEEVE': { name: 'Up My Sleeve', color: 'Silent', rarity: 'Uncommon', type: 'Skill' },
  'CARD.UPPERCUT': { name: 'Uppercut', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.UPROAR': { name: 'Uproar', color: 'Defect', rarity: 'Common', type: 'Attack' },
  'CARD.VEILPIERCER': { name: 'Veilpiercer', color: 'Necrobinder', rarity: 'Uncommon', type: 'Attack' },
  'CARD.VENERATE': { name: 'Venerate', color: 'Regent', rarity: 'Basic', type: 'Skill' },
  'CARD.VICIOUS': { name: 'Vicious', color: 'Ironclad', rarity: 'Uncommon', type: 'Power' },
  'CARD.VOID': { name: 'Void', color: 'Status', rarity: 'Status', type: 'Status' },
  'CARD.VOID_FORM': { name: 'Void Form', color: 'Regent', rarity: 'Rare', type: 'Power' },
  'CARD.VOLLEY': { name: 'Volley', color: 'Colorless', rarity: 'Uncommon', type: 'Attack' },
  'CARD.VOLTAIC': { name: 'Voltaic', color: 'Defect', rarity: 'Rare', type: 'Skill' },
  'CARD.WASTE_AWAY': { name: 'Waste Away', color: 'Token', rarity: 'Status', type: 'Status' },
  'CARD.WELL_LAID_PLANS': { name: 'Well-Laid Plans', color: 'Silent', rarity: 'Uncommon', type: 'Power' },
  'CARD.WHIRLWIND': { name: 'Whirlwind', color: 'Ironclad', rarity: 'Uncommon', type: 'Attack' },
  'CARD.WHISTLE': { name: 'Whistle', color: 'Event', rarity: 'Ancient', type: 'Attack' },
  'CARD.WHITE_NOISE': { name: 'White Noise', color: 'Defect', rarity: 'Uncommon', type: 'Skill' },
  'CARD.WISH': { name: 'Wish', color: 'Event', rarity: 'Ancient', type: 'Skill' },
  'CARD.WISP': { name: 'Wisp', color: 'Necrobinder', rarity: 'Common', type: 'Skill' },
  'CARD.WOUND': { name: 'Wound', color: 'Status', rarity: 'Status', type: 'Status' },
  'CARD.WRAITH_FORM': { name: 'Wraith Form', color: 'Silent', rarity: 'Ancient', type: 'Power' },
  'CARD.WRITHE': { name: 'Writhe', color: 'Curse', rarity: 'Curse', type: 'Curse' },
  'CARD.WROUGHT_IN_WAR': { name: 'Wrought in War', color: 'Regent', rarity: 'Common', type: 'Attack' },
  'CARD.ZAP': { name: 'Zap', color: 'Defect', rarity: 'Basic', type: 'Skill' },
};

export function getCardMeta(cardId: string): CardMeta | undefined {
  // Strip enchantment suffix like " [ENCHANTMENT.SWIFT]"
  const bracketIdx = cardId.indexOf(' [');
  const withoutEnchantment = bracketIdx !== -1 ? cardId.slice(0, bracketIdx) : cardId;
  const baseId = withoutEnchantment.endsWith('+') ? withoutEnchantment.slice(0, -1) : withoutEnchantment;
  return CARD_META[baseId];
}
