// Auto-generated from https://github.com/ptrlrd/spire-codex (v0.104.0)
// 293 relics — regenerate with: node scripts/generate-meta.mjs

export type RelicRarity = 'Ancient' | 'Common' | 'Event' | 'None' | 'Rare' | 'Shop' | 'Starter' | 'Uncommon';
export type RelicCharacter = 'Colorless' | 'Defect' | 'Ironclad' | 'Necrobinder' | 'Regent' | 'Silent';

export interface RelicMeta {
  name: string;
  character: RelicCharacter;
  rarity: RelicRarity;
}

const RELIC_META: Record<string, RelicMeta> = {
  'RELIC.AKABEKO': { name: 'Akabeko', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.ALCHEMICAL_COFFER': { name: 'Alchemical Coffer', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.AMETHYST_AUBERGINE': { name: 'Amethyst Aubergine', character: 'Colorless', rarity: 'Common' },
  'RELIC.ANCHOR': { name: 'Anchor', character: 'Colorless', rarity: 'Common' },
  'RELIC.FAKE_ANCHOR': { name: 'Anchor???', character: 'Colorless', rarity: 'Event' },
  'RELIC.ARCANE_SCROLL': { name: 'Arcane Scroll', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.ARCHAIC_TOOTH': { name: 'Archaic Tooth', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.ART_OF_WAR': { name: 'Art of War', character: 'Colorless', rarity: 'Rare' },
  'RELIC.ASTROLABE': { name: 'Astrolabe', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.BAG_OF_MARBLES': { name: 'Bag of Marbles', character: 'Colorless', rarity: 'Common' },
  'RELIC.BAG_OF_PREPARATION': { name: 'Bag of Preparation', character: 'Colorless', rarity: 'Common' },
  'RELIC.BEATING_REMNANT': { name: 'Beating Remnant', character: 'Colorless', rarity: 'Rare' },
  'RELIC.BEAUTIFUL_BRACELET': { name: 'Beautiful Bracelet', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.BELLOWS': { name: 'Bellows', character: 'Colorless', rarity: 'Rare' },
  'RELIC.BELT_BUCKLE': { name: 'Belt Buckle', character: 'Colorless', rarity: 'Shop' },
  'RELIC.BIG_HAT': { name: 'Big Hat', character: 'Necrobinder', rarity: 'Rare' },
  'RELIC.BIG_MUSHROOM': { name: 'Big Mushroom', character: 'Colorless', rarity: 'Event' },
  'RELIC.BIIIG_HUG': { name: 'Biiig Hug', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.BING_BONG': { name: 'Bing Bong', character: 'Colorless', rarity: 'Event' },
  'RELIC.BLACK_BLOOD': { name: 'Black Blood', character: 'Ironclad', rarity: 'Starter' },
  'RELIC.BLACK_STAR': { name: 'Black Star', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.BLESSED_ANTLER': { name: 'Blessed Antler', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.BLOOD_VIAL': { name: 'Blood Vial', character: 'Colorless', rarity: 'Common' },
  'RELIC.FAKE_BLOOD_VIAL': { name: 'Blood Vial???', character: 'Colorless', rarity: 'Event' },
  'RELIC.BLOOD_SOAKED_ROSE': { name: 'Blood-Soaked Rose', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.BONE_FLUTE': { name: 'Bone Flute', character: 'Necrobinder', rarity: 'Common' },
  'RELIC.BONE_TEA': { name: 'Bone Tea', character: 'Colorless', rarity: 'Event' },
  'RELIC.BOOK_REPAIR_KNIFE': { name: 'Book Repair Knife', character: 'Necrobinder', rarity: 'Uncommon' },
  'RELIC.BOOK_OF_FIVE_RINGS': { name: 'Book of Five Rings', character: 'Colorless', rarity: 'Common' },
  'RELIC.BOOKMARK': { name: 'Bookmark', character: 'Necrobinder', rarity: 'Rare' },
  'RELIC.BOOMING_CONCH': { name: 'Booming Conch', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.BOUND_PHYLACTERY': { name: 'Bound Phylactery', character: 'Necrobinder', rarity: 'Starter' },
  'RELIC.BOWLER_HAT': { name: 'Bowler Hat', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.BREAD': { name: 'Bread', character: 'Colorless', rarity: 'Shop' },
  'RELIC.BRILLIANT_SCARF': { name: 'Brilliant Scarf', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.BRIMSTONE': { name: 'Brimstone', character: 'Ironclad', rarity: 'Shop' },
  'RELIC.BRONZE_SCALES': { name: 'Bronze Scales', character: 'Colorless', rarity: 'Common' },
  'RELIC.BURNING_BLOOD': { name: 'Burning Blood', character: 'Ironclad', rarity: 'Starter' },
  'RELIC.BURNING_STICKS': { name: 'Burning Sticks', character: 'Colorless', rarity: 'Shop' },
  'RELIC.BYRDPIP': { name: 'Byrdpip', character: 'Colorless', rarity: 'Event' },
  'RELIC.CALLING_BELL': { name: 'Calling Bell', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.CANDELABRA': { name: 'Candelabra', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.CAPTAINS_WHEEL': { name: 'Captain\'s Wheel', character: 'Colorless', rarity: 'Rare' },
  'RELIC.CAULDRON': { name: 'Cauldron', character: 'Colorless', rarity: 'Shop' },
  'RELIC.CENTENNIAL_PUZZLE': { name: 'Centennial Puzzle', character: 'Colorless', rarity: 'Common' },
  'RELIC.CHANDELIER': { name: 'Chandelier', character: 'Colorless', rarity: 'Rare' },
  'RELIC.CHARONS_ASHES': { name: 'Charon\'s Ashes', character: 'Ironclad', rarity: 'Rare' },
  'RELIC.CHEMICAL_X': { name: 'Chemical X', character: 'Colorless', rarity: 'Shop' },
  'RELIC.CHOICES_PARADOX': { name: 'Choices Paradox', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.CIRCLET': { name: 'Circlet', character: 'Colorless', rarity: 'None' },
  'RELIC.CLAWS': { name: 'Claws', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.CLOAK_CLASP': { name: 'Cloak Clasp', character: 'Colorless', rarity: 'Rare' },
  'RELIC.CRACKED_CORE': { name: 'Cracked Core', character: 'Defect', rarity: 'Starter' },
  'RELIC.CROSSBOW': { name: 'Crossbow', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.CURSED_PEARL': { name: 'Cursed Pearl', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.DARKSTONE_PERIAPT': { name: 'Darkstone Periapt', character: 'Colorless', rarity: 'Event' },
  'RELIC.DATA_DISK': { name: 'Data Disk', character: 'Defect', rarity: 'Common' },
  'RELIC.DAUGHTER_OF_THE_WIND': { name: 'Daughter of the Wind', character: 'Colorless', rarity: 'Event' },
  'RELIC.DELICATE_FROND': { name: 'Delicate Frond', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.DEMON_TONGUE': { name: 'Demon Tongue', character: 'Ironclad', rarity: 'Rare' },
  'RELIC.DIAMOND_DIADEM': { name: 'Diamond Diadem', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.DINGY_RUG': { name: 'Dingy Rug', character: 'Colorless', rarity: 'Shop' },
  'RELIC.DISTINGUISHED_CAPE': { name: 'Distinguished Cape', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.DIVINE_DESTINY': { name: 'Divine Destiny', character: 'Regent', rarity: 'Starter' },
  'RELIC.DIVINE_RIGHT': { name: 'Divine Right', character: 'Regent', rarity: 'Starter' },
  'RELIC.DOLLYS_MIRROR': { name: 'Dolly\'s Mirror', character: 'Colorless', rarity: 'Shop' },
  'RELIC.DRAGON_FRUIT': { name: 'Dragon Fruit', character: 'Colorless', rarity: 'Shop' },
  'RELIC.DREAM_CATCHER': { name: 'Dream Catcher', character: 'Colorless', rarity: 'Event' },
  'RELIC.DRIFTWOOD': { name: 'Driftwood', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.DUSTY_TOME': { name: 'Dusty Tome', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.ECTOPLASM': { name: 'Ectoplasm', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.ELECTRIC_SHRYMP': { name: 'Electric Shrymp', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.EMBER_TEA': { name: 'Ember Tea', character: 'Colorless', rarity: 'Event' },
  'RELIC.EMOTION_CHIP': { name: 'Emotion Chip', character: 'Defect', rarity: 'Rare' },
  'RELIC.EMPTY_CAGE': { name: 'Empty Cage', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.ETERNAL_FEATHER': { name: 'Eternal Feather', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.FENCING_MANUAL': { name: 'Fencing Manual', character: 'Regent', rarity: 'Common' },
  'RELIC.FESTIVE_POPPER': { name: 'Festive Popper', character: 'Colorless', rarity: 'Common' },
  'RELIC.FIDDLE': { name: 'Fiddle', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.FORGOTTEN_SOUL': { name: 'Forgotten Soul', character: 'Colorless', rarity: 'Event' },
  'RELIC.FRAGRANT_MUSHROOM': { name: 'Fragrant Mushroom', character: 'Colorless', rarity: 'Event' },
  'RELIC.FRESNEL_LENS': { name: 'Fresnel Lens', character: 'Colorless', rarity: 'Event' },
  'RELIC.FROZEN_EGG': { name: 'Frozen Egg', character: 'Colorless', rarity: 'Rare' },
  'RELIC.FUNERARY_MASK': { name: 'Funerary Mask', character: 'Necrobinder', rarity: 'Uncommon' },
  'RELIC.FUR_COAT': { name: 'Fur Coat', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.GALACTIC_DUST': { name: 'Galactic Dust', character: 'Regent', rarity: 'Uncommon' },
  'RELIC.GAMBLING_CHIP': { name: 'Gambling Chip', character: 'Colorless', rarity: 'Rare' },
  'RELIC.GAME_PIECE': { name: 'Game Piece', character: 'Colorless', rarity: 'Rare' },
  'RELIC.GHOST_SEED': { name: 'Ghost Seed', character: 'Colorless', rarity: 'Shop' },
  'RELIC.GIRYA': { name: 'Girya', character: 'Colorless', rarity: 'Rare' },
  'RELIC.GLASS_EYE': { name: 'Glass Eye', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.GLITTER': { name: 'Glitter', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.GNARLED_HAMMER': { name: 'Gnarled Hammer', character: 'Colorless', rarity: 'Shop' },
  'RELIC.GOLD_PLATED_CABLES': { name: 'Gold-Plated Cables', character: 'Defect', rarity: 'Uncommon' },
  'RELIC.GOLDEN_COMPASS': { name: 'Golden Compass', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.GOLDEN_PEARL': { name: 'Golden Pearl', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.GORGET': { name: 'Gorget', character: 'Colorless', rarity: 'Common' },
  'RELIC.GREMLIN_HORN': { name: 'Gremlin Horn', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.HAND_DRILL': { name: 'Hand Drill', character: 'Colorless', rarity: 'Event' },
  'RELIC.HAPPY_FLOWER': { name: 'Happy Flower', character: 'Colorless', rarity: 'Common' },
  'RELIC.FAKE_HAPPY_FLOWER': { name: 'Happy Flower???', character: 'Colorless', rarity: 'Event' },
  'RELIC.HEFTY_TABLET': { name: 'Hefty Tablet', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.HELICAL_DART': { name: 'Helical Dart', character: 'Silent', rarity: 'Rare' },
  'RELIC.HISTORY_COURSE': { name: 'History Course', character: 'Colorless', rarity: 'Event' },
  'RELIC.HORN_CLEAT': { name: 'Horn Cleat', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.ICE_CREAM': { name: 'Ice Cream', character: 'Colorless', rarity: 'Rare' },
  'RELIC.INFUSED_CORE': { name: 'Infused Core', character: 'Defect', rarity: 'Starter' },
  'RELIC.INTIMIDATING_HELMET': { name: 'Intimidating Helmet', character: 'Colorless', rarity: 'Rare' },
  'RELIC.IRON_CLUB': { name: 'Iron Club', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.IVORY_TILE': { name: 'Ivory Tile', character: 'Necrobinder', rarity: 'Rare' },
  'RELIC.JEWELED_MASK': { name: 'Jeweled Mask', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.JEWELRY_BOX': { name: 'Jewelry Box', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.JOSS_PAPER': { name: 'Joss Paper', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.JUZU_BRACELET': { name: 'Juzu Bracelet', character: 'Colorless', rarity: 'Common' },
  'RELIC.KIFUDA': { name: 'Kifuda', character: 'Colorless', rarity: 'Shop' },
  'RELIC.KUNAI': { name: 'Kunai', character: 'Colorless', rarity: 'Rare' },
  'RELIC.KUSARIGAMA': { name: 'Kusarigama', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.LANTERN': { name: 'Lantern', character: 'Colorless', rarity: 'Common' },
  'RELIC.LARGE_CAPSULE': { name: 'Large Capsule', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.LASTING_CANDY': { name: 'Lasting Candy', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.LAVA_LAMP': { name: 'Lava Lamp', character: 'Colorless', rarity: 'Shop' },
  'RELIC.LAVA_ROCK': { name: 'Lava Rock', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.LEAD_PAPERWEIGHT': { name: 'Lead Paperweight', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.LEAFY_POULTICE': { name: 'Leafy Poultice', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.LEES_WAFFLE': { name: 'Lee\'s Waffle', character: 'Colorless', rarity: 'Shop' },
  'RELIC.FAKE_LEES_WAFFLE': { name: 'Lee\'s Waffle???', character: 'Colorless', rarity: 'Event' },
  'RELIC.LETTER_OPENER': { name: 'Letter Opener', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.LIZARD_TAIL': { name: 'Lizard Tail', character: 'Colorless', rarity: 'Rare' },
  'RELIC.LOOMING_FRUIT': { name: 'Looming Fruit', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.LORDS_PARASOL': { name: 'Lord\'s Parasol', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.LOST_COFFER': { name: 'Lost Coffer', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.LOST_WISP': { name: 'Lost Wisp', character: 'Colorless', rarity: 'Event' },
  'RELIC.LUCKY_FYSH': { name: 'Lucky Fysh', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.LUNAR_PASTRY': { name: 'Lunar Pastry', character: 'Regent', rarity: 'Rare' },
  'RELIC.MANGO': { name: 'Mango', character: 'Colorless', rarity: 'Rare' },
  'RELIC.FAKE_MANGO': { name: 'Mango???', character: 'Colorless', rarity: 'Event' },
  'RELIC.MASSIVE_SCROLL': { name: 'Massive Scroll', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.MAW_BANK': { name: 'Maw Bank', character: 'Colorless', rarity: 'Event' },
  'RELIC.MEAL_TICKET': { name: 'Meal Ticket', character: 'Colorless', rarity: 'Common' },
  'RELIC.MEAT_CLEAVER': { name: 'Meat Cleaver', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.MEAT_ON_THE_BONE': { name: 'Meat on the Bone', character: 'Colorless', rarity: 'Rare' },
  'RELIC.MEMBERSHIP_CARD': { name: 'Membership Card', character: 'Colorless', rarity: 'Shop' },
  'RELIC.MERCURY_HOURGLASS': { name: 'Mercury Hourglass', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.METRONOME': { name: 'Metronome', character: 'Defect', rarity: 'Rare' },
  'RELIC.MINI_REGENT': { name: 'Mini Regent', character: 'Regent', rarity: 'Rare' },
  'RELIC.MINIATURE_CANNON': { name: 'Miniature Cannon', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.MINIATURE_TENT': { name: 'Miniature Tent', character: 'Colorless', rarity: 'Shop' },
  'RELIC.MOLTEN_EGG': { name: 'Molten Egg', character: 'Colorless', rarity: 'Rare' },
  'RELIC.MR_STRUGGLES': { name: 'Mr. Struggles', character: 'Colorless', rarity: 'Event' },
  'RELIC.MUMMIFIED_HAND': { name: 'Mummified Hand', character: 'Colorless', rarity: 'Rare' },
  'RELIC.MUSIC_BOX': { name: 'Music Box', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.MYSTIC_LIGHTER': { name: 'Mystic Lighter', character: 'Colorless', rarity: 'Shop' },
  'RELIC.NEOWS_BONES': { name: 'Neow\'s Bones', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.NEOWS_TALISMAN': { name: 'Neow\'s Talisman', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.NEOWS_TORMENT': { name: 'Neow\'s Torment', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.NEW_LEAF': { name: 'New Leaf', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.NINJA_SCROLL': { name: 'Ninja Scroll', character: 'Silent', rarity: 'Shop' },
  'RELIC.NUNCHAKU': { name: 'Nunchaku', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.NUTRITIOUS_OYSTER': { name: 'Nutritious Oyster', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.NUTRITIOUS_SOUP': { name: 'Nutritious Soup', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.ODDLY_SMOOTH_STONE': { name: 'Oddly Smooth Stone', character: 'Colorless', rarity: 'Common' },
  'RELIC.OLD_COIN': { name: 'Old Coin', character: 'Colorless', rarity: 'Rare' },
  'RELIC.ORANGE_DOUGH': { name: 'Orange Dough', character: 'Regent', rarity: 'Rare' },
  'RELIC.ORICHALCUM': { name: 'Orichalcum', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.FAKE_ORICHALCUM': { name: 'Orichalcum???', character: 'Colorless', rarity: 'Event' },
  'RELIC.ORNAMENTAL_FAN': { name: 'Ornamental Fan', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.ORRERY': { name: 'Orrery', character: 'Colorless', rarity: 'Shop' },
  'RELIC.PAELS_BLOOD': { name: 'Pael\'s Blood', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PAELS_CLAW': { name: 'Pael\'s Claw', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PAELS_EYE': { name: 'Pael\'s Eye', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PAELS_FLESH': { name: 'Pael\'s Flesh', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PAELS_GROWTH': { name: 'Pael\'s Growth', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PAELS_HORN': { name: 'Pael\'s Horn', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PAELS_LEGION': { name: 'Pael\'s Legion', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PAELS_TEARS': { name: 'Pael\'s Tears', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PAELS_TOOTH': { name: 'Pael\'s Tooth', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PAELS_WING': { name: 'Pael\'s Wing', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PANDORAS_BOX': { name: 'Pandora\'s Box', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PANTOGRAPH': { name: 'Pantograph', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.PAPER_KRANE': { name: 'Paper Krane', character: 'Silent', rarity: 'Rare' },
  'RELIC.PAPER_PHROG': { name: 'Paper Phrog', character: 'Ironclad', rarity: 'Uncommon' },
  'RELIC.PARRYING_SHIELD': { name: 'Parrying Shield', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.PEAR': { name: 'Pear', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.PEN_NIB': { name: 'Pen Nib', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.PENDULUM': { name: 'Pendulum', character: 'Colorless', rarity: 'Common' },
  'RELIC.PERMAFROST': { name: 'Permafrost', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.PETRIFIED_TOAD': { name: 'Petrified Toad', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.PHIAL_HOLSTER': { name: 'Phial Holster', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PHILOSOPHERS_STONE': { name: 'Philosopher\'s Stone', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PHYLACTERY_UNBOUND': { name: 'Phylactery Unbound', character: 'Necrobinder', rarity: 'Starter' },
  'RELIC.PLANISPHERE': { name: 'Planisphere', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.POCKETWATCH': { name: 'Pocketwatch', character: 'Colorless', rarity: 'Rare' },
  'RELIC.POLLINOUS_CORE': { name: 'Pollinous Core', character: 'Colorless', rarity: 'Event' },
  'RELIC.POMANDER': { name: 'Pomander', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.POTION_BELT': { name: 'Potion Belt', character: 'Colorless', rarity: 'Common' },
  'RELIC.POWER_CELL': { name: 'Power Cell', character: 'Defect', rarity: 'Rare' },
  'RELIC.PRAYER_WHEEL': { name: 'Prayer Wheel', character: 'Colorless', rarity: 'Rare' },
  'RELIC.PRECARIOUS_SHEARS': { name: 'Precarious Shears', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PRECISE_SCISSORS': { name: 'Precise Scissors', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PRESERVED_FOG': { name: 'Preserved Fog', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PRISMATIC_GEM': { name: 'Prismatic Gem', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PUMPKIN_CANDLE': { name: 'Pumpkin Candle', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.PUNCH_DAGGER': { name: 'Punch Dagger', character: 'Colorless', rarity: 'Shop' },
  'RELIC.RADIANT_PEARL': { name: 'Radiant Pearl', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.RAINBOW_RING': { name: 'Rainbow Ring', character: 'Colorless', rarity: 'Rare' },
  'RELIC.RAZOR_TOOTH': { name: 'Razor Tooth', character: 'Colorless', rarity: 'Rare' },
  'RELIC.RED_MASK': { name: 'Red Mask', character: 'Colorless', rarity: 'Common' },
  'RELIC.RED_SKULL': { name: 'Red Skull', character: 'Ironclad', rarity: 'Common' },
  'RELIC.REGAL_PILLOW': { name: 'Regal Pillow', character: 'Colorless', rarity: 'Common' },
  'RELIC.REGALITE': { name: 'Regalite', character: 'Regent', rarity: 'Uncommon' },
  'RELIC.REPTILE_TRINKET': { name: 'Reptile Trinket', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.RING_OF_THE_DRAKE': { name: 'Ring of the Drake', character: 'Silent', rarity: 'Starter' },
  'RELIC.RING_OF_THE_SNAKE': { name: 'Ring of the Snake', character: 'Silent', rarity: 'Starter' },
  'RELIC.RINGING_TRIANGLE': { name: 'Ringing Triangle', character: 'Colorless', rarity: 'Shop' },
  'RELIC.RIPPLE_BASIN': { name: 'Ripple Basin', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.ROYAL_POISON': { name: 'Royal Poison', character: 'Colorless', rarity: 'Event' },
  'RELIC.ROYAL_STAMP': { name: 'Royal Stamp', character: 'Colorless', rarity: 'Shop' },
  'RELIC.RUINED_HELMET': { name: 'Ruined Helmet', character: 'Ironclad', rarity: 'Rare' },
  'RELIC.RUNIC_CAPACITOR': { name: 'Runic Capacitor', character: 'Defect', rarity: 'Shop' },
  'RELIC.RUNIC_PYRAMID': { name: 'Runic Pyramid', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.SAI': { name: 'Sai', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.SAND_CASTLE': { name: 'Sand Castle', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.SCREAMING_FLAGON': { name: 'Screaming Flagon', character: 'Colorless', rarity: 'Shop' },
  'RELIC.SCROLL_BOXES': { name: 'Scroll Boxes', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.SEA_GLASS': { name: 'Sea Glass', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.SEAL_OF_GOLD': { name: 'Seal of Gold', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.SELF_FORMING_CLAY': { name: 'Self-Forming Clay', character: 'Ironclad', rarity: 'Uncommon' },
  'RELIC.SERE_TALON': { name: 'Sere Talon', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.SHOVEL': { name: 'Shovel', character: 'Colorless', rarity: 'Rare' },
  'RELIC.SHURIKEN': { name: 'Shuriken', character: 'Colorless', rarity: 'Rare' },
  'RELIC.SIGNET_RING': { name: 'Signet Ring', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.SILVER_CRUCIBLE': { name: 'Silver Crucible', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.SLING_OF_COURAGE': { name: 'Sling of Courage', character: 'Colorless', rarity: 'Shop' },
  'RELIC.SMALL_CAPSULE': { name: 'Small Capsule', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.SNECKO_EYE': { name: 'Snecko Eye', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.FAKE_SNECKO_EYE': { name: 'Snecko Eye???', character: 'Colorless', rarity: 'Event' },
  'RELIC.SNECKO_SKULL': { name: 'Snecko Skull', character: 'Silent', rarity: 'Common' },
  'RELIC.SOZU': { name: 'Sozu', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.SPARKLING_ROUGE': { name: 'Sparkling Rouge', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.SPIKED_GAUNTLETS': { name: 'Spiked Gauntlets', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.STONE_CALENDAR': { name: 'Stone Calendar', character: 'Colorless', rarity: 'Rare' },
  'RELIC.STONE_CRACKER': { name: 'Stone Cracker', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.STONE_HUMIDIFIER': { name: 'Stone Humidifier', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.STORYBOOK': { name: 'Storybook', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.STRAWBERRY': { name: 'Strawberry', character: 'Colorless', rarity: 'Common' },
  'RELIC.STRIKE_DUMMY': { name: 'Strike Dummy', character: 'Colorless', rarity: 'Common' },
  'RELIC.FAKE_STRIKE_DUMMY': { name: 'Strike Dummy???', character: 'Colorless', rarity: 'Event' },
  'RELIC.STURDY_CLAMP': { name: 'Sturdy Clamp', character: 'Colorless', rarity: 'Rare' },
  'RELIC.SWORD_OF_JADE': { name: 'Sword of Jade', character: 'Colorless', rarity: 'Event' },
  'RELIC.SWORD_OF_STONE': { name: 'Sword of Stone', character: 'Colorless', rarity: 'Event' },
  'RELIC.SYMBIOTIC_VIRUS': { name: 'Symbiotic Virus', character: 'Defect', rarity: 'Uncommon' },
  'RELIC.TANXS_WHISTLE': { name: 'Tanx\'s Whistle', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.TEA_OF_DISCOURTESY': { name: 'Tea of Discourtesy', character: 'Colorless', rarity: 'Event' },
  'RELIC.THE_ABACUS': { name: 'The Abacus', character: 'Colorless', rarity: 'Shop' },
  'RELIC.THE_BOOT': { name: 'The Boot', character: 'Colorless', rarity: 'Event' },
  'RELIC.CHOSEN_CHEESE': { name: 'The Chosen Cheese', character: 'Colorless', rarity: 'Event' },
  'RELIC.THE_COURIER': { name: 'The Courier', character: 'Colorless', rarity: 'Rare' },
  'RELIC.FAKE_MERCHANTS_RUG': { name: 'The Merchant\'s Rug???', character: 'Colorless', rarity: 'Event' },
  'RELIC.THROWING_AXE': { name: 'Throwing Axe', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.TINGSHA': { name: 'Tingsha', character: 'Silent', rarity: 'Uncommon' },
  'RELIC.TINY_MAILBOX': { name: 'Tiny Mailbox', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.TOASTY_MITTENS': { name: 'Toasty Mittens', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.TOOLBOX': { name: 'Toolbox', character: 'Colorless', rarity: 'Shop' },
  'RELIC.TOUCH_OF_OROBAS': { name: 'Touch of Orobas', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.TOUGH_BANDAGES': { name: 'Tough Bandages', character: 'Silent', rarity: 'Rare' },
  'RELIC.TOXIC_EGG': { name: 'Toxic Egg', character: 'Colorless', rarity: 'Rare' },
  'RELIC.TOY_BOX': { name: 'Toy Box', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.TRI_BOOMERANG': { name: 'Tri-Boomerang', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.TUNGSTEN_ROD': { name: 'Tungsten Rod', character: 'Colorless', rarity: 'Rare' },
  'RELIC.TUNING_FORK': { name: 'Tuning Fork', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.TWISTED_FUNNEL': { name: 'Twisted Funnel', character: 'Silent', rarity: 'Uncommon' },
  'RELIC.UNCEASING_TOP': { name: 'Unceasing Top', character: 'Colorless', rarity: 'Rare' },
  'RELIC.UNDYING_SIGIL': { name: 'Undying Sigil', character: 'Necrobinder', rarity: 'Shop' },
  'RELIC.UNSETTLING_LAMP': { name: 'Unsettling Lamp', character: 'Colorless', rarity: 'Rare' },
  'RELIC.VAJRA': { name: 'Vajra', character: 'Colorless', rarity: 'Common' },
  'RELIC.VAMBRACE': { name: 'Vambrace', character: 'Colorless', rarity: 'Uncommon' },
  'RELIC.VELVET_CHOKER': { name: 'Velvet Choker', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.VENERABLE_TEA_SET': { name: 'Venerable Tea Set', character: 'Colorless', rarity: 'Common' },
  'RELIC.FAKE_VENERABLE_TEA_SET': { name: 'Venerable Tea Set???', character: 'Colorless', rarity: 'Event' },
  'RELIC.VERY_HOT_COCOA': { name: 'Very Hot Cocoa', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.VEXING_PUZZLEBOX': { name: 'Vexing Puzzlebox', character: 'Colorless', rarity: 'Rare' },
  'RELIC.VITRUVIAN_MINION': { name: 'Vitruvian Minion', character: 'Regent', rarity: 'Shop' },
  'RELIC.WAR_HAMMER': { name: 'War Hammer', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.WAR_PAINT': { name: 'War Paint', character: 'Colorless', rarity: 'Common' },
  'RELIC.WHETSTONE': { name: 'Whetstone', character: 'Colorless', rarity: 'Common' },
  'RELIC.WHISPERING_EARRING': { name: 'Whispering Earring', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.WHITE_BEAST_STATUE': { name: 'White Beast Statue', character: 'Colorless', rarity: 'Rare' },
  'RELIC.WHITE_STAR': { name: 'White Star', character: 'Colorless', rarity: 'Rare' },
  'RELIC.WING_CHARM': { name: 'Wing Charm', character: 'Colorless', rarity: 'Shop' },
  'RELIC.WINGED_BOOTS': { name: 'Winged Boots', character: 'Colorless', rarity: 'Ancient' },
  'RELIC.WONGO_CUSTOMER_APPRECIATION_BADGE': { name: 'Wongo Customer Appreciation Badge', character: 'Colorless', rarity: 'Event' },
  'RELIC.WONGOS_MYSTERY_TICKET': { name: 'Wongo\'s Mystery Ticket', character: 'Colorless', rarity: 'Event' },
  'RELIC.YUMMY_COOKIE': { name: 'Yummy Cookie', character: 'Colorless', rarity: 'Ancient' },
};

export function getRelicMeta(id: string): RelicMeta | undefined {
  return RELIC_META[id];
}
